# Generated by tile-rs mlir_to_tpu — DO NOT EDIT
# Run: python <file.py> on a TPU VM with JAX installed

import jax
import jax.numpy as jnp
from jax.experimental import pallas as pl
from functools import partial

def rsum(

    p0_ref,
    p1_ref
):
    t0 = p0_ref[...]
    t1 = jnp.sum(t0, axis=-1, keepdims=True)
    p1_ref[...] = t1

@jax.jit
def rsum_pallas(x0):
    return pl.pallas_call(
        rsum,
        out_shape=jax.ShapeDtypeStruct(x0.shape, x0.dtype),
    )(x0)

