# Generated by tile-rs mlir_to_nki — DO NOT EDIT
# Compile: neuronx-cc compile --framework nki --target trn1 <file.py>

import neuronxcc.nki as nki
import neuronxcc.nki.language as nl
import neuronxcc.nki.isa as nisa
import numpy as np

@nki.jit
def rsum(p0, p1):
    t0 = nl.load(p0[nl.mgrid[0:1, 0:256]])
    t1 = nisa.tensor_reduce(np.add, t0, axis=(1,), dtype=np.float32, negate=False)
    nl.store(p1[nl.mgrid[0:1, 0:256]], t1)

