// Generated by tile-rs mlir_to_gaudi — DO NOT EDIT
// Compile: tpc-clang -march=gaudi2 -O2 <file>.gaudi.c

#include <stdint.h>

// rsum: rows=1, cols=256
void main(tensor input0, tensor output0) {
    int5 index = get_index_space_offset();
    int5 end   = get_index_space_size();

    while (index[0] < end[0]) {
        float256 v_0 = v_f32_ld_tnsr(index, input0);
        float v_1 = v_f32_reduce_add(v_0);
        v_f32_st_tnsr(index, output0, v_1);

        index[0] += get_index_space_stride()[0];
    }
}
