// Generated by tile-rs mlir_to_musa — DO NOT EDIT
// Compile: mcc -arch=mp_22 -O3 <file>.musa.mu -o <file>.ptx --ptx
// Or:      clang++ --musa-gpu-arch=mp_22 -O3 <file>.musa.mu -S -emit-llvm

#include <musa_runtime.h>
#include <musa_fp16.h>
#include <math.h>
#include <stdint.h>

// Warp-level reduction helpers (result valid in ALL lanes)
__device__ __forceinline__ float warp_reduce_max(float val) {
    for (int offset = 16; offset > 0; offset >>= 1)
        val = fmaxf(val, __shfl_xor_sync(0xffffffff, val, offset));
    return val;
}

__device__ __forceinline__ float warp_reduce_sum(float val) {
    for (int offset = 16; offset > 0; offset >>= 1)
        val += __shfl_xor_sync(0xffffffff, val, offset);
    return val;
}

// Half-precision warp reduction helpers (via float promotion)
__device__ __forceinline__ __half warp_reduce_max_f16(__half val) {
    return (__half)warp_reduce_max((float)val);
}

__device__ __forceinline__ __half warp_reduce_sum_f16(__half val) {
    return (__half)warp_reduce_sum((float)val);
}

// rsum: rows=1, cols=256
// Launch: <<<num_tiles, 256>>>
__launch_bounds__(256) __global__ void rsum(const float* __restrict__ p0, float* __restrict__ p1) {
    // safety: sdata must fit in per-block shared memory
    static_assert(8 * sizeof(float) <= 49152, "sdata exceeds mp_22 48KB shared-mem budget");
    __shared__ float sdata[8];
    const int tid  = threadIdx.x;
    const int goff = blockIdx.x * 256 + tid;
    float _v0 = p0[goff];
    // block-wide sum reduce — warp phase only (assumes N<=32)
    float _v1 = warp_reduce_sum((float)_v0);
    p1[goff] = _v1;
}

