# Generated by tile-rs mlir_to_aie — DO NOT EDIT
# Compile: python3 <this_file> npu2 > design.mlir
# Simulate: aiecc.py --aiesim design.mlir

import sys
import numpy as np
from aie.iron import ObjectFifo, Program, Runtime, Worker
from aie.iron.placers import SequentialPlacer
from aie.iron.device import NPU1Col1, NPU2Col1
from aie.iron.controlflow import range_
from aie.dialects import math as aie_math
from aie.dialects.arith import MaxNumFOp, AddFOp
from aie.dialects.scf import yield_

TILE_WIDTH   = 256
_PROBLEM_SIZE_DEFAULT = 256
PROBLEM_SIZE = int(sys.argv[2]) if len(sys.argv) > 2 else _PROBLEM_SIZE_DEFAULT
N_TILES      = PROBLEM_SIZE // TILE_WIDTH
MEM_WIDTH    = TILE_WIDTH * max(N_TILES, 2)  # MemTile ping-pong buffer

if len(sys.argv) > 1 and sys.argv[1] == "npu":
    _dev = NPU1Col1()
else:
    _dev = NPU2Col1()

def rsum():
    tile_ty = np.ndarray[(TILE_WIDTH,), np.dtype[np.float32]]
    mem_ty  = np.ndarray[(MEM_WIDTH,), np.dtype[np.float32]]
    all_ty  = np.ndarray[(PROBLEM_SIZE,), np.dtype[np.float32]]

    of_in0a = ObjectFifo(mem_ty,  name="in0")
    of_in0b = of_in0a.cons().forward(obj_type=tile_ty)
    of_out0a = ObjectFifo(tile_ty, name="out0")
    of_out0b = of_out0a.cons().forward(obj_type=mem_ty)

    def core_body(of_in0b, of_out0a):
        for _ in range_(sys.maxsize):
            elem_in0 = of_in0b.acquire(1)
            elem_out0 = of_out0a.acquire(1)
            for _ri, __rsum_0_i, _rsum_0 in range_(1, TILE_WIDTH, iter_args=[elem_in0[0]], insert_yield=False):
                yield_([AddFOp(__rsum_0_i, elem_in0[_ri]).result])
            of_in0b.release(1)
            of_out0a.release(1)

    worker = Worker(core_body, fn_args=[of_in0b.cons(), of_out0a.prod()])

    rt = Runtime()
    with rt.sequence(all_ty, all_ty) as (t0, t1):
        rt.start(worker)
        rt.fill(of_in0a.prod(),    t0)
        rt.drain(of_out0b.cons(),  t1, wait=True)

    return Program(_dev, rt).resolve_program(SequentialPlacer())

module = rsum()
res = module.operation.verify()
if res == True:
    print(module)
else:
    print(res)
