// Generated by tile-rs mlir_to_rvv — DO NOT EDIT
// Target: RISC-V rv64gcv (RVV 1.0), via the linalg bridge.
//
// Lower with:  scripts/rvv_lower.sh <this_file> -o kernel.s
//
// which runs, in order:
//   mlir-opt -transform-preload-library=\
//              transform-library-paths=scripts/rvv_decompose.mlir \
//            -transform-interpreter \
//            -linalg-generalize-named-ops \
//            -one-shot-bufferize=bufferize-function-boundaries \
//            -convert-linalg-to-affine-loops \
//            -affine-super-vectorize=virtual-vector-size=<VL> \
//            -lower-affine -convert-scf-to-cf -convert-vector-to-llvm \
//            -convert-math-to-llvm -convert-math-to-libm ...
//   mlir-translate --mlir-to-llvmir
//   opt -O3
//   llc -mtriple=riscv64 -mattr=+v,+zvl128b,+d
//
// NOTE: -affine-super-vectorize is load-bearing. Without it the loop
// vectoriser does not fire on the lowered memrefs and llc emits scalar
// flw/fadd.s/fsw — correct, and roughly VLEN/32 times too slow.

module attributes {
  llvm.target_triple = "riscv64-unknown-linux-gnu",
  llvm.data_layout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
} {

  func.func @rsum(%arg0: tensor<1x256xf32>) -> tensor<1xf32> {
    %t0 = arith.constant 0.000000e+00 : f32
    %t1 = tensor.empty() : tensor<1xf32>
    %t2 = linalg.fill ins(%t0 : f32) outs(%t1 : tensor<1xf32>) -> tensor<1xf32>
    %t3 = linalg.reduce ins(%arg0 : tensor<1x256xf32>) outs(%t2 : tensor<1xf32>) dimensions = [1]
      (%in: f32, %acc: f32) {
        %r = arith.addf %in, %acc : f32
        linalg.yield %r : f32
      }
    return %t3 : tensor<1xf32>
  }

}
