// Generated by tile-rs mlir_to_linalg — DO NOT EDIT
// Verify: mlir-opt --verify-diagnostics <this_file>

func.func @rsum(%arg0: tensor<1x256xf32>) -> tensor<1xf32> {
  %t0 = arith.constant 0.000000e+00 : f32
  %t1 = tensor.empty() : tensor<1xf32>
  %t2 = linalg.fill ins(%t0 : f32) outs(%t1 : tensor<1xf32>) -> tensor<1xf32>
  %t3 = linalg.reduce ins(%arg0 : tensor<1x256xf32>) outs(%t2 : tensor<1xf32>) dimensions = [1]
    (%in: f32, %acc: f32) {
      %r = arith.addf %in, %acc : f32
      linalg.yield %r : f32
    }
  return %t3 : tensor<1xf32>
}

