; Generated by tile-rs mlir_to_pico -- DO NOT EDIT
; target : PICO / SVP_NNN (dpicoV100), 7-bit opcode, 8-byte word
; build  : svp assembles this listing -- asm_pico -> PackPicoOm -> .om
;          there is no ptoas on this path.
;
; Values are SYMBOLIC. UB addressing, bank groups, events and register
; allocation are resolved by pypto; this listing states the op program only.
;
; @manifest
; {
;   "abi": "pico-op-program-v1",
;   "kernel": "rsum",
;   "part": "dpicoV100",
;   "npu_arch": "V100",
;   "gm_params": 2,
;   "dims": [1, 256],
;   "eps": null,
;   "dtype_contract": {
;     "kernel_value": "f32",
;     "vector_engine": "f16",
;     "cube_engine": "s8",
;     "note": "f32 kernel values are converted at the DDR/UB boundary; the vector engine is f16 native."
;   },
;   "l0_model": "programmatic-over-ub",
;   "ub_geometry": { "bank_groups": 8, "rams_per_group": 16, "ram_depth": 1024, "word_bytes": 16 },
;   "ub_bytes": 2097152,
;   "ownership": {
;     "tile_rs": ["op program", "shapes", "dtype contract", "fusion groups"],
;     "pypto": ["UB addressing", "bank-group allocation", "event barriers", "register allocation"],
;     "svp": ["intrinsic assembly", "PackPicoOm", ".om container"]
;   },
;   "intrinsic_evidence": {
;     "dld": "ExecutionVerified",
;     "dstr": "ExecutionVerified",
;     "vsum": "OwnerSpecified"
;   },
;   "unattested_intrinsics": [],
;   "backend_obligations": [],
;   "gm_resident": [],
;   "ops": [
;     { "op": "load", "unit": "mte", "folded": 1, "intrinsics": ["dld"] },
;     { "op": "reduce_sum", "unit": "vector", "folded": 1, "intrinsics": ["vsum"] },
;     { "op": "store", "unit": "mte", "folded": 1, "intrinsics": ["dstr"] }
;   ]
; }
; @end-manifest

.kernel rsum
.part   dpicoV100 (V100)
.dtype  kernel=f32 vector=f16 cube=s8   ; converted at the DDR/UB boundary
.l0     programmatic-over-ub          ; no physical L0A/L0B/L0C; cube operands are UB bank-group residencies
.ub     2097152 bytes, 4 banks, bg_ram_num=16
.gm     2 tensors

  ; [0] load %a <- %arg0, %r, %c
  dld      ; op=0x4e  DDR -> UB
  ; [1] reduce_sum %y <- %a, %a, %r, %c
  vsum     ; op=0x39  reduction
  ; [2] store _ <- %arg1, %y, %r, %c
  dstr     ; op=0x52  UB -> DDR

  end      ; op=0x22

; intrinsics used: dld dstr vsum
