// Generated by tile-rs mlir_to_rvv — DO NOT EDIT
// Target: RISC-V rv64gcv (RVV 1.0), via the linalg bridge.
//
// Lower with:  scripts/rvv_lower.sh <this_file> -o kernel.s
//
// which runs, in order:
//   mlir-opt -transform-preload-library=\
//              transform-library-paths=scripts/rvv_decompose.mlir \
//            -transform-interpreter \
//            -linalg-generalize-named-ops \
//            -one-shot-bufferize=bufferize-function-boundaries \
//            -convert-linalg-to-affine-loops \
//            -affine-super-vectorize=virtual-vector-size=<VL> \
//            -lower-affine -convert-scf-to-cf -convert-vector-to-llvm \
//            -convert-math-to-llvm -convert-math-to-libm ...
//   mlir-translate --mlir-to-llvmir
//   opt -O3
//   llc -mtriple=riscv64 -mattr=+v,+zvl128b,+d
//
// NOTE: -affine-super-vectorize is load-bearing. Without it the loop
// vectoriser does not fire on the lowered memrefs and llc emits scalar
// flw/fadd.s/fsw — correct, and roughly VLEN/32 times too slow.

module attributes {
  llvm.target_triple = "riscv64-unknown-linux-gnu",
  llvm.data_layout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
} {

  func.func @softmax_1d(%arg0: tensor<1x1024xf32>) -> tensor<1x1024xf32> {
    %t0 = tensor.empty() : tensor<1x1024xf32>
    %t1 = linalg.softmax dimension(1) ins(%arg0 : tensor<1x1024xf32>) outs(%t0 : tensor<1x1024xf32>) -> tensor<1x1024xf32>
    return %t1 : tensor<1x1024xf32>
  }

}
