// Generated by tile-rs mlir_to_linalg — DO NOT EDIT
// Verify: mlir-opt --verify-diagnostics <this_file>

func.func @softmax_1d(%arg0: tensor<1x1024xf32>) -> tensor<1x1024xf32> {
  %t0 = tensor.empty() : tensor<1x1024xf32>
  %t1 = linalg.softmax dimension(1) ins(%arg0 : tensor<1x1024xf32>) outs(%t0 : tensor<1x1024xf32>) -> tensor<1x1024xf32>
  return %t1 : tensor<1x1024xf32>
}

