// Generated by tile-rs mlir_to_gpu — DO NOT EDIT
// Compile: nvcc -arch=sm_80 -O3 <file>.gpu.cu -o <file>.ptx --ptx
// Or:      clang++ --cuda-gpu-arch=sm_80 -O3 <file>.gpu.cu -S -emit-llvm

#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <math.h>
#include <stdint.h>

// Warp-level reduction helpers (result valid in ALL lanes)
__device__ __forceinline__ float warp_reduce_max(float val) {
    for (int offset = 16; offset > 0; offset >>= 1)
        val = fmaxf(val, __shfl_xor_sync(0xffffffff, val, offset));
    return val;
}

__device__ __forceinline__ float warp_reduce_sum(float val) {
    for (int offset = 16; offset > 0; offset >>= 1)
        val += __shfl_xor_sync(0xffffffff, val, offset);
    return val;
}

// Half-precision warp reduction helpers (via float promotion)
__device__ __forceinline__ __half warp_reduce_max_f16(__half val) {
    return (__half)warp_reduce_max((float)val);
}

__device__ __forceinline__ __half warp_reduce_sum_f16(__half val) {
    return (__half)warp_reduce_sum((float)val);
}

// softmax_1d: rows=1, cols=1024
// Launch: <<<num_tiles, 1024>>>
__launch_bounds__(1024) __global__ void softmax_1d(const float* __restrict__ p0, float* __restrict__ p1) {
    // safety: sdata must fit in per-block shared memory
    static_assert(32 * sizeof(float) <= 49152, "sdata exceeds sm_80 48KB shared-mem budget");
    __shared__ float sdata[32];
    const int tid  = threadIdx.x;
    const int goff = blockIdx.x * 1024 + tid;
    float _v0 = p0[goff];
    // softmax step 1: block-wide max (N=1024)
    float _wmax1 = warp_reduce_max((float)_v0);
    if ((tid & 31) == 0) sdata[tid >> 5] = _wmax1;
    __syncthreads();
    if (tid < 32) {
        float _wmax1_p = (tid < 32) ? sdata[tid] : -INFINITY;
        _wmax1 = warp_reduce_max(_wmax1_p);
        if (tid == 0) sdata[0] = _wmax1;
    }
    __syncthreads();
    float _row_max2 = sdata[0];
    __syncthreads();
    // softmax steps 2-3: exp(x - max)
    float _exp3 = expf((float)_v0 - _row_max2);
    // softmax step 4: block-wide sum
    float _wsum4 = warp_reduce_sum(_exp3);
    if ((tid & 31) == 0) sdata[tid >> 5] = _wsum4;
    __syncthreads();
    if (tid < 32) {
        float _wsum4_p = (tid < 32) ? sdata[tid] : 0.0f;
        _wsum4 = warp_reduce_sum(_wsum4_p);
        if (tid == 0) sdata[0] = _wsum4;
    }
    __syncthreads();
    float _row_sum5 = sdata[0];
    __syncthreads();
    // softmax step 5: normalise
    float _v6 = _exp3 / _row_sum5;
    p1[goff] = _v6;
}

