// Generated by tile-rs mlir_to_ttmetal — DO NOT EDIT
// Compile: loaded via TT-Metal CreateKernel(..., TENSIX) on Wormhole/Blackhole.
//
// Circular-buffer layout (matches host-side ascendrs_ttmetal launcher):
//   cb_in0  = tt::CB::c_in0   (GM input 0)
//   cb_in1  = tt::CB::c_in1   (GM input 1, unused for unary ops)
//   cb_out  = tt::CB::c_out0  (GM output)

#include "compute_kernel_api/common.h"
#include "compute_kernel_api/softmax.h"

namespace NAMESPACE {
// kernel: softmax_1d
void MAIN {
    constexpr auto cb_in0 = tt::CB::c_in0;
    constexpr auto cb_in1 = tt::CB::c_in1;
    constexpr auto cb_out = tt::CB::c_out0;

    init_sfpu(cb_in0, cb_out);
    softmax_tile_init();

    cb_wait_front(cb_in0, 1);
    cb_reserve_back(cb_out, 1);
    acquire_dst();
    copy_tile(cb_in0, 0, 0);
    softmax_tile(0);
    pack_tile(0, cb_out);
    release_dst();
    cb_pop_front(cb_in0, 1);
    cb_push_back(cb_out, 1);
}
}  // namespace NAMESPACE
