// Generated by tile-rs mlir_to_hexagon — DO NOT EDIT
// Compile: hexagon-clang -mv75 -O2 -c <file>.c
// Target:  Qualcomm Hexagon HTP (Snapdragon 8 Gen 3 / X Elite, HVX v73+)
//
// This source is the kernel half of a QNN Op Package. Pair it with
// the XML descriptor produced by qnn-op-package-generator to load
// under QnnHtp at runtime.

#include "HTP/core/ops.h"
#include "HTP/hvx_utils.h"
#include "HTP/hvx_softmax.h"

// kernel: softmax_1d
void execute_softmax_1d(const float* in0, float* out, int n) {
    hvx_softmax_f32(in0, out, n);
}

// TODO(tier2): emit QNN Op Package XML + interfaceProvider.
//   Run `qnn-op-package-generator -p ascendrs.xml` to populate.
