// Generated by tile-rs mlir_to_gaudi — DO NOT EDIT
// Compile: tpc-clang -march=gaudi2 -O2 <file>.gaudi.c

#include <stdint.h>

// softmax_1d: rows=1, cols=1024
void main(tensor input0, tensor output0) {
    int5 index = get_index_space_offset();
    int5 end   = get_index_space_size();

    while (index[0] < end[0]) {
        float256 v_0 = v_f32_ld_tnsr(index, input0);
        // softmax step 1: max reduction
        float _sfx_max = v_f32_reduce_max(v_0);
        // softmax step 2: broadcast max
        float256 _sfx_max_v = v_f32_mov_scalar(_sfx_max);
        // softmax step 3: exp(x - max)
        float256 _sfx_shifted = v_f32_sub(v_0, _sfx_max_v);
        float256 v_1 = v_f32_exp(_sfx_shifted);
        // softmax step 4: sum reduction
        float _sfx_sum = v_f32_reduce_add(v_1);
        // softmax step 5: divide (rcp + mul)
        float256 _sfx_sum_v = v_f32_mov_scalar(_sfx_sum);
        float256 _sfx_inv = v_f32_rcp(_sfx_sum_v);
        v_1 = v_f32_mul(v_1, _sfx_inv);
        v_f32_st_tnsr(index, output0, v_1);

        index[0] += get_index_space_stride()[0];
    }
}
