// Generated by tile-rs mlir_to_msl — DO NOT EDIT
// Compile: xcrun metal -c <file>.metal -o <file>.air && xcrun metallib <file>.air -o <file>.metallib
// Runtime: metal::Device::new_library_with_source(src, &CompileOptions::new())

#include <metal_stdlib>
using namespace metal;

kernel void softmax_1d(
    device const  float* p0 [[ buffer(0) ]],
    device  float* p1 [[ buffer(1) ]],
    constant uint& num_elements [[ buffer(2) ]],
    uint tid   [[ thread_position_in_threadgroup ]],
    uint row   [[ threadgroup_position_in_grid ]],
    uint tcount [[ threads_per_threadgroup ]]
)
{
    constexpr uint MAX_TG = 1024;
    threadgroup float sdata[MAX_TG];
    uint base = row * num_elements;

    // Pass 1: find row max
    float tmax = -MAXFLOAT;
    for (uint i = tid; i < num_elements; i += tcount)
        tmax = max(tmax, p0[base + i]);
    sdata[tid] = tmax;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (tid == 0) {
        for (uint i = 1; i < tcount; i++) sdata[0] = max(sdata[0], sdata[i]);
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float row_max = sdata[0];

    // Pass 2: exp(x - max), accumulate sum
    float tsum = 0.0f;
    for (uint i = tid; i < num_elements; i += tcount) {
        float e = exp(float(p0[base + i]) - float(row_max));
        tsum += e;
    }
    sdata[tid] = tsum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    if (tid == 0) {
        for (uint i = 1; i < tcount; i++) sdata[0] += sdata[i];
    }
    threadgroup_barrier(mem_flags::mem_threadgroup);
    float row_sum = sdata[0];

    // Pass 3: normalise
    for (uint i = tid; i < num_elements; i += tcount)
        p1[base + i] = exp(float(p0[base + i]) - float(row_max)) / row_sum;
}

