# Generated by tile-rs mlir_to_tpu — DO NOT EDIT
# Run: python <file.py> on a TPU VM with JAX installed

import jax
import jax.numpy as jnp
from jax.experimental import pallas as pl
from functools import partial

def softmax_1d(

    p0_ref,
    p1_ref
):
    t0 = p0_ref[...]
    _tmp0 = jnp.max(t0, axis=-1, keepdims=True)
    _tmp1 = t0 - _tmp0
    _tmp2 = jnp.exp(_tmp1)
    _tmp3 = jnp.sum(_tmp2, axis=-1, keepdims=True)
    t1 = _tmp2 / _tmp3
    p1_ref[...] = t1

@jax.jit
def softmax_1d_pallas(x0):
    return pl.pallas_call(
        softmax_1d,
        out_shape=jax.ShapeDtypeStruct(x0.shape, x0.dtype),
    )(x0)

