# Generated by tile-rs mlir_to_nki — DO NOT EDIT
# Compile: neuronx-cc compile --framework nki --target trn1 <file.py>

import neuronxcc.nki as nki
import neuronxcc.nki.language as nl
import neuronxcc.nki.isa as nisa
import numpy as np

@nki.jit
def softmax_1d(p0, p1):
    t0 = nl.load(p0[nl.mgrid[0:1, 0:1024]])
    _tmp0 = nisa.tensor_reduce(np.max, t0, axis=(1,), dtype=np.float32, negate=False)
    _tmp1 = nisa.tensor_scalar(t0, np.subtract, _tmp0, dtype=np.float32)
    _tmp2 = nisa.activation(np.exp, _tmp1, dtype=np.float32)
    _tmp3 = nisa.tensor_reduce(np.add, _tmp2, axis=(1,), dtype=np.float32, negate=False)
    t1 = nl.divide(_tmp2, _tmp3)
    nl.store(p1[nl.mgrid[0:1, 0:1024]], t1)

