// SPDX-License-Identifier: Apache-2.0
//
//! `mlir_to_hexagon` — Qualcomm Hexagon / HTP op-package emitter.
//!
//! # Target
//! - Qualcomm Snapdragon NPUs (Hexagon HTP — Hexagon Tensor Processor), as
//!   shipped in Snapdragon 8 Gen series (`v73`, `v75`, `v79`) phones and
//!   Snapdragon X Elite laptops.
//! - Emitted kernels live in a QNN "Op Package" compiled with the Qualcomm
//!   Hexagon SDK's `hexagon-clang` / `qnn-op-package-generator` toolchain
//!   and loaded at runtime by the QNN HTP backend
//!   (`libQnnHtp.so` / `QnnHtp.dll`).
//!
//! # Scope of this first version
//! Same 5 Table-2 kernels as the other vendor emitters:
//! softmax, rms_norm (with `eps` param), add, exp, matmul.
//!
//! For each MLIR function we emit:
//!
//! 1. A thin `execute_<kernel>()` free function using the QNN HTP
//!    `HVX_Vector`-level primitives (`hvx_vmpy_f`, `hvx_vexp_f`, etc.),
//!    wrapped as a QNN custom op via the standard op-package shim.
//! 2. The op-package registration footer (`OpPackage_interfaceProvider`
//!    stub) — stubbed out by default; it is filled in by the
//!    `qnn-op-package-generator` CLI on the rented Snapdragon Cloud VM.
//!
//! This Tier-1 source is *compilable* with `hexagon-clang -mv75 -O2 -c`
//! on any Snapdragon Cloud (or AIHub bring-up) instance with the Hexagon
//! SDK installed. Tier-2 on-device execution requires writing the QNN
//! Op Package XML + wiring the op into a graph, which is scaffolded as
//! TODO in `benchmarks/qualcomm/bench_ascendrs_qnn.py`.
//!
//! # Intrinsic mapping (element-wise, fp32 HVX)
//! | tile-rs intrinsic           | Hexagon HVX primitive                               |
//! |-------------------------------|------------------------------------------------------|
//! | `__tile_load_f32`        | `hvx_vload_f32_aligned(src, n)`                      |
//! | `__tile_store_f32`       | `hvx_vstore_f32_aligned(dst, v, n)`                  |
//! | `__tile_add_f32`         | `hvx_vadd_f32(a, b, out, n)`                         |
//! | `__tile_exp_f32`         | `hvx_vexp_f32(x, out, n)`                            |
//! | `__tile_softmax_f32`     | `hvx_softmax_f32(x, out, n)` (SDK util)              |
//! | `__tile_rms_norm_f32`    | `hvx_rms_norm_f32(x, out, n, eps)`                   |
//! | `__tile_matmul_f32`      | `hvx_matmul_f32(a, b, out, M, K, N)` (blocked MAC)   |
//!
//! The HVX utility functions are thin wrappers around the public HTP
//! intrinsics; the op-package generator links them from
//! `$QNN_SDK_ROOT/share/QNN/HtpUtils/`.
//!
//! # Example output
//! ```c
//! // Generated by tile-rs mlir_to_hexagon — DO NOT EDIT
//! // Compile: hexagon-clang -mv75 -O2 -c <file>.c
//! #include "HTP/core/ops.h"
//! #include "HTP/hvx_softmax.h"
//! void execute_tile_softmax(const float* in0, float* out, int n) {
//!     hvx_softmax_f32(in0, out, n);
//! }
//! ```
//!
//! Run under `benchmarks/qualcomm/bench_ascendrs_qnn.py` on a rented
//! Snapdragon Cloud / AIHub instance — compile-only Tier 1 today, device
//! run Tier 2 is tracked as TODO.

use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
enum Op {
    Load,
    Store,
    Add,
    Exp,
    Softmax,
    RmsNorm,
    Matmul,
    Unknown,
}

fn classify_callee(callee: &str) -> Op {
    if callee.contains("__tile_load_") {
        Op::Load
    } else if callee.contains("__tile_store_") {
        Op::Store
    } else if callee.contains("__tile_add_") {
        Op::Add
    } else if callee.contains("__tile_exp_") {
        Op::Exp
    } else if callee.contains("__tile_softmax_") {
        Op::Softmax
    } else if callee.contains("__tile_rms_norm_") {
        Op::RmsNorm
    } else if callee.contains("__tile_matmul_") {
        Op::Matmul
    } else {
        Op::Unknown
    }
}

fn extract_call_callee(line: &str) -> Option<&str> {
    let at = line.find('@')?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(&rest[..end])
}

fn extract_fn_name(line: &str) -> Option<String> {
    let at = line.find("@")?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(rest[..end].to_string())
}

fn count_entry_ptrs(line: &str) -> usize {
    // Count "!llvm.ptr<1>" occurrences in a function signature.
    line.matches("!llvm.ptr<1>").count()
}

fn required_headers(ops: &[Op]) -> Vec<&'static str> {
    let mut hs: Vec<&'static str> = vec!["HTP/core/ops.h", "HTP/hvx_utils.h"];
    let mut seen: HashMap<&'static str, ()> = HashMap::new();
    for h in &hs {
        seen.insert(*h, ());
    }
    for op in ops {
        let h = match op {
            Op::Add => "HTP/hvx_eltwise.h",
            Op::Exp => "HTP/hvx_exp.h",
            Op::Softmax => "HTP/hvx_softmax.h",
            Op::RmsNorm => "HTP/hvx_rms_norm.h",
            Op::Matmul => "HTP/hvx_matmul.h",
            _ => continue,
        };
        if seen.insert(h, ()).is_none() {
            hs.push(h);
        }
    }
    hs
}

/// Scan for an `eps` f32 literal bound to `__tile_rms_norm_*` arg 2.
/// Returns the resolved literal (e.g. `"1.0e-5f"`) or a safe default.
fn find_rms_eps(mlir_text: &str) -> String {
    let mut f32_map: HashMap<String, String> = HashMap::new();
    let mut eps_ssa: Option<String> = None;
    for raw in mlir_text.lines() {
        let line = raw.trim();
        // Prescan f32 constants.
        if line.contains("llvm.mlir.constant") && (line.contains(": f32") || line.contains(": f16"))
        {
            // shape: %eps = llvm.mlir.constant(1.0e-5 : f32) : f32
            if let Some(eq) = line.find('=') {
                let lhs = line[..eq].trim();
                if let (Some(l), Some(r)) = (line.find('('), line.find(')')) {
                    let inside = &line[l + 1..r];
                    if let Some(colon) = inside.find(" :") {
                        let lit = inside[..colon].trim();
                        if !lit.is_empty() && lhs.starts_with('%') {
                            f32_map.insert(lhs.to_string(), lit.to_string());
                        }
                    }
                }
            }
        }
        if line.contains("llvm.call @__tile_rms_norm_") {
            // shape: llvm.call @__tile_rms_norm_f32(%x, %x, %eps, %r, %c)
            if let (Some(l), Some(r)) = (line.find('('), line.rfind(')')) {
                let args: Vec<&str> = line[l + 1..r].split(',').map(str::trim).collect();
                if args.len() >= 3 {
                    eps_ssa = Some(args[2].to_string());
                }
            }
        }
    }
    if let Some(ssa) = eps_ssa {
        if let Some(lit) = f32_map.get(&ssa) {
            let mut s = lit.to_string();
            if !s.ends_with('f') && !s.ends_with('F') {
                s.push('f');
            }
            return s;
        }
    }
    "1.0e-5f".to_string()
}

fn emit_execute_body(op: Op, eps: &str, out: &mut String) {
    match op {
        Op::Add => {
            out.push_str("    hvx_vadd_f32(in0, in1, out, n);\n");
        }
        Op::Exp => {
            out.push_str("    hvx_vexp_f32(in0, out, n);\n");
        }
        Op::Softmax => {
            out.push_str("    hvx_softmax_f32(in0, out, n);\n");
        }
        Op::RmsNorm => {
            out.push_str(&format!("    hvx_rms_norm_f32(in0, out, n, {});\n", eps));
        }
        Op::Matmul => {
            out.push_str("    hvx_matmul_f32(in0, in1, out, M, K, N);\n");
        }
        _ => {}
    }
}

fn primary_op(ops: &[Op]) -> Op {
    for op in ops {
        match op {
            Op::Add | Op::Exp | Op::Softmax | Op::RmsNorm | Op::Matmul => return *op,
            _ => {}
        }
    }
    Op::Unknown
}

/// Convert MLIR with `__tile_*` intrinsics into a QNN HTP op-package
/// compute kernel (Hexagon C source).
pub fn convert_mlir_to_hexagon(mlir_text: &str) -> Result<String, String> {
    let mut fn_name: Option<String> = None;
    let mut n_ptrs: usize = 0;
    let mut ops: Vec<Op> = Vec::new();
    for raw in mlir_text.lines() {
        let line = raw.trim();
        if line.starts_with("llvm.func @") {
            fn_name = extract_fn_name(line);
            n_ptrs = count_entry_ptrs(line);
        }
        if line.contains("llvm.call @__tile_") {
            if let Some(callee) = extract_call_callee(line) {
                let op = classify_callee(callee);
                if op != Op::Unknown && op != Op::Load && op != Op::Store {
                    ops.push(op);
                }
            }
        }
    }
    let fn_name = fn_name.unwrap_or_else(|| "tile_kernel".to_string());
    let eps = find_rms_eps(mlir_text);
    let op = primary_op(&ops);

    let mut out = String::new();
    out.push_str("// Generated by tile-rs mlir_to_hexagon — DO NOT EDIT\n");
    out.push_str("// Compile: hexagon-clang -mv75 -O2 -c <file>.c\n");
    out.push_str("// Target:  Qualcomm Hexagon HTP (Snapdragon 8 Gen 3 / X Elite, HVX v73+)\n");
    out.push_str("//\n");
    out.push_str("// This source is the kernel half of a QNN Op Package. Pair it with\n");
    out.push_str("// the XML descriptor produced by qnn-op-package-generator to load\n");
    out.push_str("// under QnnHtp at runtime.\n");
    out.push_str("\n");
    for h in required_headers(&ops) {
        out.push_str(&format!("#include \"{}\"\n", h));
    }
    out.push_str("\n");
    out.push_str(&format!("// kernel: {}\n", fn_name));

    // Emit an execute_<kernel>() entry point. Matmul takes (M,K,N);
    // element-wise ops take a single (n) length.
    match op {
        Op::Matmul => {
            out.push_str(&format!(
                "void execute_{}(const float* in0, const float* in1, float* out,\n",
                fn_name
            ));
            out.push_str("                               int M, int K, int N) {\n");
            emit_execute_body(op, &eps, &mut out);
            out.push_str("}\n");
        }
        Op::Add => {
            out.push_str(&format!(
                "void execute_{}(const float* in0, const float* in1, float* out, int n) {{\n",
                fn_name
            ));
            emit_execute_body(op, &eps, &mut out);
            out.push_str("}\n");
        }
        Op::Exp | Op::Softmax | Op::RmsNorm => {
            out.push_str(&format!(
                "void execute_{}(const float* in0, float* out, int n) {{\n",
                fn_name
            ));
            emit_execute_body(op, &eps, &mut out);
            out.push_str("}\n");
        }
        _ => {
            // Generic fallback — identity copy, matches unary signature.
            out.push_str(&format!(
                "void execute_{}(const float* in0, float* out, int n) {{\n",
                fn_name
            ));
            out.push_str("    hvx_vcopy_f32(in0, out, n);\n");
            out.push_str("}\n");
        }
    }

    // Op-package registration stub. Real packages register via
    // OpPackage_interfaceProvider; we emit a placeholder the bring-up
    // notebook fills in alongside the generated XML descriptor.
    out.push_str("\n// TODO(tier2): emit QNN Op Package XML + interfaceProvider.\n");
    out.push_str("//   Run `qnn-op-package-generator -p ascendrs.xml` to populate.\n");

    // Silence unused variable warnings for n_ptrs — captured for future
    // multi-arg op validation.
    let _ = n_ptrs;

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hexagon_softmax() {
        let mlir = r#"
module {
  llvm.func @tile_softmax(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %x = llvm.call @__tile_load_f32(%a, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @__tile_softmax_f32(%x, %x, %r, %c) : (i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%b, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let c = convert_mlir_to_hexagon(mlir).unwrap();
        assert!(c.contains("HTP/hvx_softmax.h"));
        assert!(c.contains("void execute_tile_softmax"));
        assert!(c.contains("hvx_softmax_f32(in0, out, n);"));
    }

    #[test]
    fn test_hexagon_matmul() {
        let mlir = r#"
module {
  llvm.func @tile_matmul(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>, %c: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %m = llvm.mlir.constant(128 : i32) : i32
    %k = llvm.mlir.constant(128 : i32) : i32
    %n = llvm.mlir.constant(128 : i32) : i32
    %al = llvm.call @__tile_load_f32(%a, %m, %k) : (!llvm.ptr<1>, i32, i32) -> i32
    %bl = llvm.call @__tile_load_f32(%b, %k, %n) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @__tile_matmul_f32(%al, %al, %bl, %m, %k, %n) : (i32, i32, i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%c, %y, %m, %n) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let c = convert_mlir_to_hexagon(mlir).unwrap();
        assert!(c.contains("HTP/hvx_matmul.h"));
        assert!(c.contains("void execute_tile_matmul"));
        assert!(c.contains("hvx_matmul_f32(in0, in1, out, M, K, N);"));
    }

    #[test]
    fn test_hexagon_rms_norm_eps_resolved() {
        let mlir = r#"
module {
  llvm.func @tile_layernorm(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %eps = llvm.mlir.constant(1.0e-5 : f32) : f32
    %x = llvm.call @__tile_load_f32(%a, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @__tile_rms_norm_f32(%x, %x, %eps, %r, %c) : (i32, i32, f32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%b, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let c = convert_mlir_to_hexagon(mlir).unwrap();
        assert!(c.contains("HTP/hvx_rms_norm.h"));
        assert!(c.contains("hvx_rms_norm_f32(in0, out, n, 1.0e-5f);"));
        assert!(!c.contains("%eps"));
    }

    #[test]
    fn test_hexagon_add_two_inputs() {
        let mlir = r#"
module {
  llvm.func @tile_add(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>, %c: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %n = llvm.mlir.constant(1024 : i32) : i32
    %x = llvm.call @__tile_load_f32(%a, %r, %n) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @__tile_load_f32(%b, %r, %n) : (!llvm.ptr<1>, i32, i32) -> i32
    %z = llvm.call @__tile_add_f32(%x, %x, %y, %r, %n) : (i32, i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%c, %z, %r, %n) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let c = convert_mlir_to_hexagon(mlir).unwrap();
        assert!(c.contains("hvx_vadd_f32(in0, in1, out, n);"));
        assert!(c.contains("const float* in0, const float* in1, float* out, int n"));
    }
}
