// SPDX-License-Identifier: Apache-2.0
//
// @generated by the tile-rs-pico backend repository, scripts/vendor_to_tile_rs.sh
// -- DO NOT EDIT BY HAND.
//
//   crates/pico_isa      -> module `pico_isa` below
//   crates/pico_codegen  -> the rest of this file
//
// Regenerate by running that script against a tile-rs tree. No URL is given
// here on purpose: that repository is not published, and a comment pointing at
// a 404 is worse than one that simply names the source.

// Only `convert_mlir_to_pico` is re-exported by rustc_codegen_tile; the rest of
// the intrinsic model is carried along deliberately and is exercised by the
// tests at the bottom of this file.
#![forbid(unsafe_code)]
#![allow(dead_code)]

pub mod pico_isa {
    // SPDX-License-Identifier: Apache-2.0
    //
    //! `pico_isa` — the PICO / SVP_NNN intrinsic set, as a field-exact Rust model.
    //!
    //! # Why this crate exists
    //!
    //! Every other tile-rs backend ends in a vendor *compiler*: CUDA has `nvcc`,
    //! Ascend has `ptoas`/bisheng, Hexagon has `hexagon-clang`. PICO has none of
    //! that. The whole toolchain below tile-rs is:
    //!
    //! ```text
    //!   tile_std kernel -> MLIR -> mlir_to_pico -> .pico.s + .pico.json
    //!                                                  |
    //!                                     svp assembles intrinsics
    //!                                                  v
    //!                                       PackPicoOm -> .om -> board
    //! ```
    //!
    //! So the *intrinsic set is the target language*. This crate is the tile-rs-side
    //! model of it: 96 architectural slots (the opcode is 7 bits at `word[0:6]`, and
    //! `0x00..=0x5F` is the disclosed space), each with the bit layout svp uses to
    //! encode and decode real `.om` instruction streams.
    //!
    //! # Provenance and honesty
    //!
    //! The table is *generated* from svp's own tables (`scripts/gen_isa_table.py`), so
    //! it cannot drift into invention. Each slot carries a [`Status`]:
    //!
    //! - [`Status::FieldsVerified`] — layout round-trips against real `.om` words
    //!   (svp `asm_pico.py roundtrip`), or was proven by execution-grounded mutation.
    //! - [`Status::FieldsInferred`] — mnemonic is owner-disclosed, layout follows the
    //!   verified convention for its class but has not itself been round-tripped.
    //! - [`Status::NameOnly`] — owner-disclosed mnemonic, fields not yet modeled.
    //! - [`Status::Unassigned`] — slot in the architectural space with no disclosed
    //!   mnemonic (`0x5B..=0x5F`).
    //!
    //! Codegen must refuse to emit anything weaker than `FieldsVerified` unless the
    //! caller explicitly opts in — see [`Intrinsic::is_emittable`].

    #![forbid(unsafe_code)]

    mod table {
        // SPDX-License-Identifier: Apache-2.0
        //
        // @generated by scripts/gen_isa_table.py -- DO NOT EDIT BY HAND.
        // Source of truth: svp/scripts/disasm_pico.py (mnemonics, per-op decoders) and
        // svp/scripts/asm_pico.py (FIELDS: round-trip-verified bit layouts).
        //
        // 96 intrinsic slots (7-bit opcode, 0x00..0x5F); 91 named by svp,
        // 5 unassigned. Regenerate: SVP=~/svp python3 scripts/gen_isa_table.py

        use super::{Class, Field, Intrinsic, Status};

        /// Every architectural intrinsic slot, indexed by opcode.
        pub static INTRINSICS: [Intrinsic; 96] = [
            Intrinsic { op: 0x00, name: Some("add"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x01, name: Some("addc"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x02, name: Some("addi"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x03, name: Some("addic"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x04, name: Some("sub"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x05, name: Some("subc"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x06, name: Some("subi"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x07, name: Some("subic"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x08, name: Some("mul"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x09, name: Some("muli"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0a, name: Some("abs"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0b, name: Some("div"), class: Class::Scalar, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0c, name: Some("max"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0d, name: Some("maxi"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0e, name: Some("min"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x0f, name: Some("mini"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x10, name: Some("cmp"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x11, name: Some("cmpi"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x12, name: Some("and"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x13, name: Some("andi"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x14, name: Some("or"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x15, name: Some("ori"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x16, name: Some("xor"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x17, name: Some("not"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x18, name: Some("shl"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x19, name: Some("shli"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("imm", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1a, name: Some("shr"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("src2", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1b, name: Some("shri"), class: Class::Scalar, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("type", 7, 4), Field::new("Xd", 11, 6), Field::new("Xn", 17, 6), Field::new("imm5", 23, 5), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1c, name: Some("mov"), class: Class::Scalar, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("mode", 7, 3), Field::new("dst", 10, 16), Field::new("src", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1d, name: Some("ldxr"), class: Class::Scalar, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1e, name: Some("stxr"), class: Class::Scalar, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x1f, name: Some("insert"), class: Class::Scalar, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x20, name: Some("cvt"), class: Class::Scalar, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x21, name: Some("nop"), class: Class::Control, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x22, name: Some("end"), class: Class::Control, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x23, name: Some("trap"), class: Class::Control, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x24, name: Some("jmp"), class: Class::Control, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("mode", 7, 4), Field::new("Xd", 11, 6), Field::new("dst", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x25, name: Some("jc"), class: Class::Control, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("mode", 7, 4), Field::new("Xd", 11, 6), Field::new("dst", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x26, name: Some("jnc"), class: Class::Control, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("mode", 7, 4), Field::new("Xd", 11, 6), Field::new("dst", 31, 32), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x27, name: Some("jdnz"), class: Class::Control, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x28, name: Some("bar"), class: Class::Control, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x29, name: Some("enew"), class: Class::Event, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("Xd", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2a, name: Some("eset"), class: Class::Event, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("Xn", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2b, name: Some("ewait"), class: Class::Event, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("Xn", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2c, name: Some("fset"), class: Class::Event, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("flag", 11, 5), Field::new("value", 16, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2d, name: Some("actva"), class: Class::Bank, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("va_off", 11, 21), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2e, name: Some("allocbg"), class: Class::Bank, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("count", 11, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x2f, name: Some("rmpvbg"), class: Class::Bank, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("bgid", 11, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x30, name: Some("frvbg"), class: Class::Bank, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("bgid", 11, 4), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x31, name: Some("ldgp"), class: Class::Glp, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("xn", 11, 6), Field::new("xraddr", 17, 16), Field::new("glpid", 33, 8), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x32, name: Some("sglp"), class: Class::Glp, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("xn", 11, 6), Field::new("xm", 17, 6), Field::new("glpid", 23, 8), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x33, name: Some("vlut"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x34, name: Some("vsltc"), class: Class::Vector, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("src", 17, 6), Field::new("xt", 23, 6), Field::new("clip_en", 35, 1), Field::new("mask_en", 36, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x35, name: Some("vexp"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x36, name: Some("vlog"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x37, name: Some("vdiv"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x38, name: Some("vsqrt"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x39, name: Some("vsum"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3a, name: Some("vmax"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3b, name: Some("vmin"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3c, name: Some("vnot"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3d, name: Some("vsemad"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3e, name: Some("vvasltc"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x3f, name: Some("vvadd"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x40, name: Some("vvsub"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x41, name: Some("vvmul"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x42, name: Some("vvdiv"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x43, name: Some("vvmad"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x44, name: Some("vvmax"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x45, name: Some("vvmin"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x46, name: Some("vvcmp"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x47, name: Some("vvand"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x48, name: Some("vvor"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x49, name: Some("vvxor"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4a, name: Some("vbfilter"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4b, name: Some("vbsort"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4c, name: Some("vbnms"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4d, name: Some("imgld"), class: Class::Memory, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4e, name: Some("dld"), class: Class::Memory, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("type", 7, 4), Field::new("Xd", 11, 6), Field::new("Xn64", 17, 6), Field::new("Xt", 23, 6), Field::new("swid", 35, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x4f, name: Some("pld"), class: Class::Memory, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("type", 7, 4), Field::new("Xd", 11, 6), Field::new("Xn64", 17, 6), Field::new("Xt", 23, 6), Field::new("swid", 35, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x50, name: Some("dtrans"), class: Class::Memory, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("Xd", 11, 6), Field::new("Xn", 17, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x51, name: Some("dcpy"), class: Class::Memory, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("Xd", 11, 6), Field::new("Xn", 17, 6), Field::new("Xt", 23, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x52, name: Some("dstr"), class: Class::Memory, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("type", 7, 4), Field::new("Xd64", 11, 6), Field::new("src", 17, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x53, name: Some("mmad"), class: Class::Cube, status: Status::FieldsVerified, fields: &[Field::new("op", 0, 7), Field::new("subop", 7, 3), Field::new("bias", 10, 1), Field::new("Xd", 11, 6), Field::new("Xn", 17, 6), Field::new("Xm", 23, 6), Field::new("Xt", 29, 6), Field::new("active", 35, 1), Field::new("k1x1", 36, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x54, name: Some("pool"), class: Class::Cube, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x55, name: Some("fwait"), class: Class::Event, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("flag", 11, 5), Field::new("value", 16, 1), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x56, name: Some("neg"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x57, name: Some("cnew"), class: Class::Event, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("cevent", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x58, name: Some("cset"), class: Class::Event, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("cevent", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x59, name: Some("cget"), class: Class::Event, status: Status::FieldsInferred, fields: &[Field::new("op", 0, 7), Field::new("pipe", 7, 4), Field::new("cevent", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x5a, name: Some("dwarp"), class: Class::Vector, status: Status::NameOnly, fields: &[Field::new("op", 0, 7), Field::new("dst", 11, 6), Field::new("f63", 63, 1)] },
            Intrinsic { op: 0x5b, name: None, class: Class::Unknown, status: Status::Unassigned, fields: &[] },
            Intrinsic { op: 0x5c, name: None, class: Class::Unknown, status: Status::Unassigned, fields: &[] },
            Intrinsic { op: 0x5d, name: None, class: Class::Unknown, status: Status::Unassigned, fields: &[] },
            Intrinsic { op: 0x5e, name: None, class: Class::Unknown, status: Status::Unassigned, fields: &[] },
            Intrinsic { op: 0x5f, name: None, class: Class::Unknown, status: Status::Unassigned, fields: &[] },
        ];
    }

    pub use table::INTRINSICS;

    /// The PICO instruction word is a fixed 8 bytes, little-endian.
    pub const WORD_SIZE: usize = 8;

    /// Architectural intrinsic slots: the opcode field is 7 bits, and `0x00..=0x5F`
    /// is the disclosed space.
    pub const NUM_SLOTS: usize = 96;

    /// Opcode field: `word[0:6]`.
    pub const OPCODE_MASK: u64 = 0x7F;

    /// One bit-field of an instruction word.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub struct Field {
        pub name: &'static str,
        pub lo: u8,
        pub width: u8,
    }

    impl Field {
        pub const fn new(name: &'static str, lo: u8, width: u8) -> Self {
            Self { name, lo, width }
        }

        /// Mask of this field in word position.
        pub const fn mask(&self) -> u64 {
            (((1u128 << self.width) - 1) as u64) << self.lo
        }

        pub const fn get(&self, word: u64) -> u64 {
            (word >> self.lo) & (((1u128 << self.width) - 1) as u64)
        }
    }

    /// Compiler-facing grouping. Deliberately *not* a vendor pipeline label — these
    /// names are what the scheduler and the emitter reason about.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum Class {
        /// Integer ALU on the scalar register file.
        Scalar,
        /// Branches, `nop`/`end`/`trap`/`bar`.
        Control,
        /// Event and flag synchronisation (`enew`/`eset`/`ewait`, `fset`/`fwait`, `c*`).
        Event,
        /// Virtual bank-group lifetime and VA-space activation.
        Bank,
        /// Global/local parameter slots (`sglp`, `ldgp`).
        Glp,
        /// Vector engine (FP16 elementwise, reductions, SFU, LUT).
        Vector,
        /// Data movement between DDR, XRAM and UB.
        Memory,
        /// Cube / MAC and pooling.
        Cube,
        /// Slot with no disclosed mnemonic.
        Unknown,
    }

    /// How much of a slot is actually trustworthy.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
    pub enum Status {
        Unassigned,
        NameOnly,
        FieldsInferred,
        FieldsVerified,
    }

    /// One architectural intrinsic slot.
    #[derive(Debug, Clone, Copy)]
    pub struct Intrinsic {
        pub op: u8,
        pub name: Option<&'static str>,
        pub class: Class,
        pub status: Status,
        pub fields: &'static [Field],
    }

    impl Intrinsic {
        /// Mnemonic, or `?op=0xNN` for an unassigned slot.
        pub fn mnemonic(&self) -> String {
            self.name.map(str::to_string).unwrap_or_else(|| format!("?op=0x{:02x}", self.op))
        }

        /// Union of every modeled field — the bits this crate can account for.
        pub fn covered_mask(&self) -> u64 {
            self.fields.iter().fold(0, |m, f| m | f.mask())
        }

        /// Only verified layouts may be emitted by default. Emitting an inferred
        /// layout into a real `.om` risks a silently wrong board result, which is
        /// worse than a compile error.
        pub fn is_emittable(&self) -> bool {
            self.status == Status::FieldsVerified
        }

        pub fn field(&self, name: &str) -> Option<&'static Field> {
            self.fields.iter().find(|f| f.name == name)
        }
    }

    /// Look up an intrinsic by opcode. Opcodes above `0x5F` are outside the
    /// disclosed space and yield `None`.
    pub fn lookup(op: u8) -> Option<&'static Intrinsic> {
        INTRINSICS.get(op as usize)
    }

    /// Opcodes whose byte-0 value can be grafted onto an existing compute word to
    /// retarget the operation, leaving every other field intact.
    ///
    /// This is the one transformation that can produce *bytes* today without a
    /// verified field layout, because it does not need one: the surrounding word is
    /// the donor's and stays untouched. svp states the property for the
    /// compare/select family and backs it with execution-grounded mutation —
    /// "Grafting between these values cleanly retargets the operation
    /// (e.g. 0x44 <-> 0x45 = max <-> min), proven by mutation"
    /// (`pico_inst.h`, `PicoCompareOp`).
    ///
    /// Nothing else is listed. A family here is a licence to change what a real
    /// model computes, so it takes evidence of that kind, not a family resemblance.
    pub const COMPARE_SELECT_FAMILY: &[u8] = &[0x40, 0x42, 0x44, 0x45, 0x46];

    /// The op-portable family an opcode belongs to, if any.
    pub fn portable_family(op: u8) -> Option<&'static [u8]> {
        COMPARE_SELECT_FAMILY.contains(&op).then_some(COMPARE_SELECT_FAMILY)
    }

    /// Whether one opcode may be grafted in place of another.
    pub fn is_portable_swap(from: u8, to: u8) -> bool {
        match (portable_family(from), portable_family(to)) {
            (Some(a), Some(b)) => std::ptr::eq(a, b),
            _ => false,
        }
    }

    /// Look up an intrinsic by mnemonic.
    pub fn by_name(name: &str) -> Option<&'static Intrinsic> {
        INTRINSICS.iter().find(|i| i.name == Some(name))
    }

    /// Opcode of a word.
    pub const fn opcode(word: u64) -> u8 {
        (word & OPCODE_MASK) as u8
    }

    /// Pipe selector, `word[7:10]` — meaningful only for pipe-carrying intrinsics.
    pub const PIPES: [&str; 9] = ["s", "xr", "dld", "pld", "dst", "ubt", "ubm", "m", "v"];

    pub fn pipe_name(word: u64) -> &'static str {
        let p = ((word >> 7) & 0xF) as usize;
        PIPES.get(p).copied().unwrap_or("?")
    }

    /// Decoded fields of one word, in declaration order.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Decoded {
        pub op: u8,
        pub values: Vec<(&'static str, u64)>,
        /// Bits set in the word but outside every modeled field. A complete model
        /// leaves this at zero (or at a stable flag bit).
        pub uncovered: u64,
    }

    impl Decoded {
        pub fn get(&self, name: &str) -> Option<u64> {
            self.values.iter().find(|(n, _)| *n == name).map(|(_, v)| *v)
        }
    }

    /// Errors from encoding.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub enum IsaError {
        /// Opcode outside the 96-slot disclosed space.
        OutOfSpace(u8),
        /// Slot has no disclosed mnemonic.
        Unassigned(u8),
        /// Slot's field layout is not verified and the caller did not opt in.
        NotEmittable { op: u8, name: &'static str, status: Status },
        /// Field is not part of this intrinsic.
        UnknownField { op: u8, field: String },
        /// Value does not fit the field width.
        ValueTooWide { field: &'static str, width: u8, value: u64 },
    }

    impl core::fmt::Display for IsaError {
        fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
            match self {
                IsaError::OutOfSpace(op) => write!(f, "opcode 0x{op:02x} is outside the 96-slot PICO intrinsic space"),
                IsaError::Unassigned(op) => write!(f, "intrinsic slot 0x{op:02x} has no disclosed mnemonic"),
                IsaError::NotEmittable { op, name, status } => write!(
                    f,
                    "refusing to emit `{name}` (0x{op:02x}): field layout is {status:?}, not FieldsVerified"
                ),
                IsaError::UnknownField { op, field } => write!(f, "0x{op:02x} has no field `{field}`"),
                IsaError::ValueTooWide { field, width, value } => {
                    write!(f, "value {value} does not fit field `{field}` ({width} bits)")
                }
            }
        }
    }

    impl std::error::Error for IsaError {}

    /// Decode a word against its opcode's field model.
    pub fn decode(word: u64) -> Result<Decoded, IsaError> {
        let op = opcode(word);
        let i = lookup(op).ok_or(IsaError::OutOfSpace(op))?;
        let values = i.fields.iter().map(|f| (f.name, f.get(word))).collect();
        Ok(Decoded { op, values, uncovered: word & !i.covered_mask() })
    }

    /// Encode a word from `(field, value)` pairs. Unlisted fields are zero.
    ///
    /// Refuses slots whose layout is not [`Status::FieldsVerified`]; use
    /// [`encode_unchecked`] to override that with eyes open.
    pub fn encode(mnemonic: &str, fields: &[(&str, u64)]) -> Result<u64, IsaError> {
        let i = by_name(mnemonic).ok_or_else(|| IsaError::UnknownField {
            op: 0,
            field: mnemonic.to_string(),
        })?;
        if !i.is_emittable() {
            return Err(IsaError::NotEmittable { op: i.op, name: i.name.unwrap_or("?"), status: i.status });
        }
        encode_unchecked(i, fields)
    }

    /// Encode without the `FieldsVerified` gate. For characterisation harnesses that
    /// deliberately probe inferred layouts.
    pub fn encode_unchecked(i: &Intrinsic, fields: &[(&str, u64)]) -> Result<u64, IsaError> {
        let mut w: u64 = i.op as u64;
        for (name, value) in fields {
            if *name == "op" {
                continue;
            }
            let f = i.field(name).ok_or_else(|| IsaError::UnknownField {
                op: i.op,
                field: (*name).to_string(),
            })?;
            let max = ((1u128 << f.width) - 1) as u64;
            if *value > max {
                return Err(IsaError::ValueTooWide { field: f.name, width: f.width, value: *value });
            }
            w |= value << f.lo;
        }
        Ok(w)
    }

    /// One-line disassembly, in the same shape svp's `disasm_pico.py` prints.
    pub fn disasm(word: u64) -> String {
        let op = opcode(word);
        let Some(i) = lookup(op) else {
            return format!("?op=0x{op:02x}      (outside the 96-slot space)");
        };
        let Some(name) = i.name else {
            return format!("?op=0x{op:02x}      pipe={} reg={}", pipe_name(word), (word >> 11) & 0x3F);
        };
        let operands: Vec<String> = i
            .fields
            .iter()
            .filter(|f| f.name != "op" && f.name != "f63")
            .map(|f| {
                if f.name == "pipe" {
                    format!("pipe={}", pipe_name(word))
                } else {
                    format!("{}={}", f.name, f.get(word))
                }
            })
            .collect();
        let suffix = match i.status {
            Status::FieldsVerified => "",
            Status::FieldsInferred => "  [inferred]",
            Status::NameOnly => "  [fields TBD]",
            Status::Unassigned => "  [unassigned]",
        };
        format!("{:<8} {}{}", name, operands.join(" "), suffix)
    }

    /// Split an instruction-stream byte slice into little-endian words.
    pub fn words_from_bytes(bytes: &[u8]) -> Vec<u64> {
        bytes
            .chunks_exact(WORD_SIZE)
            .map(|c| u64::from_le_bytes(c.try_into().expect("chunks_exact(8)")))
            .collect()
    }

    /// Serialise words back to a little-endian byte stream.
    pub fn words_to_bytes(words: &[u64]) -> Vec<u8> {
        words.iter().flat_map(|w| w.to_le_bytes()).collect()
    }

    /// Summary of how much of the intrinsic space is modeled well enough to emit.
    #[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
    pub struct Coverage {
        pub slots: usize,
        pub named: usize,
        pub verified: usize,
        pub inferred: usize,
        pub name_only: usize,
        pub unassigned: usize,
    }

    pub fn coverage() -> Coverage {
        let mut c = Coverage { slots: NUM_SLOTS, ..Default::default() };
        for i in INTRINSICS.iter() {
            if i.name.is_some() {
                c.named += 1;
            }
            match i.status {
                Status::FieldsVerified => c.verified += 1,
                Status::FieldsInferred => c.inferred += 1,
                Status::NameOnly => c.name_only += 1,
                Status::Unassigned => c.unassigned += 1,
            }
        }
        c
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn the_space_is_96_slots() {
            assert_eq!(INTRINSICS.len(), NUM_SLOTS);
            for (idx, i) in INTRINSICS.iter().enumerate() {
                assert_eq!(i.op as usize, idx, "table must be indexed by opcode");
            }
        }

        #[test]
        fn coverage_matches_svp_tables() {
            let c = coverage();
            assert_eq!(c.slots, 96);
            assert_eq!(c.named, 91, "svp names 91 of the 96 slots");
            assert_eq!(c.unassigned, 5, "0x5B..=0x5F carry no disclosed mnemonic");
            assert_eq!(c.named + c.unassigned, c.slots);
        }

        #[test]
        fn known_landmarks() {
            assert_eq!(by_name("mmad").unwrap().op, 0x53);
            assert_eq!(by_name("dld").unwrap().op, 0x4e);
            assert_eq!(by_name("vvadd").unwrap().op, 0x3f);
            assert_eq!(by_name("ewait").unwrap().op, 0x2b);
            assert_eq!(lookup(0x22).unwrap().name, Some("end"));
            assert_eq!(lookup(0x5b).unwrap().name, None);
        }

        #[test]
        fn fields_do_not_overlap() {
            for i in INTRINSICS.iter() {
                let mut seen: u64 = 0;
                for f in i.fields {
                    assert_eq!(seen & f.mask(), 0, "0x{:02x} field `{}` overlaps", i.op, f.name);
                    seen |= f.mask();
                }
            }
        }

        #[test]
        fn encode_decode_round_trip() {
            let w = encode("mmad", &[("Xd", 3), ("Xn", 5), ("Xm", 7), ("Xt", 9), ("bias", 1)]).unwrap();
            let d = decode(w).unwrap();
            assert_eq!(d.op, 0x53);
            assert_eq!(d.get("Xd"), Some(3));
            assert_eq!(d.get("Xm"), Some(7));
            assert_eq!(d.get("bias"), Some(1));
            assert_eq!(d.uncovered, 0);
        }

        #[test]
        fn emission_is_gated_on_verified_layouts() {
            // `addi` is owner-named and its dst/src/imm extents follow the landmark,
            // but the layout has never been round-tripped and the real corpus shows
            // it varying bits the model did not declare. Emitting it silently would
            // drop those bits -- the dangerous option.
            let err = encode("addi", &[("dst", 1)]).unwrap_err();
            assert!(matches!(err, IsaError::NotEmittable { op: 0x02, .. }), "{err:?}");
            // `mmad` is in svp's round-trip table, so it emits.
            assert!(encode("mmad", &[("Xd", 1), ("Xn", 2), ("Xm", 3)]).is_ok());
        }

        #[test]
        fn only_round_tripped_layouts_are_verified() {
            // Exactly the opcodes svp round-trips against real OMs (asm_pico.py
            // FIELDS). Convention, however convincing, is not evidence -- an earlier
            // table promoted the whole `*i` family off the addi landmark and the
            // no-operand ops off "they have no operands", and the corpus refuted
            // both. Pinning the set stops that drifting back in.
            let verified: Vec<&str> = INTRINSICS
                .iter()
                .filter(|i| i.status == Status::FieldsVerified)
                .filter_map(|i| i.name)
                .collect();
            assert_eq!(
                verified,
                vec![
                    "shri", "mov", "jmp", "jc", "jnc", "enew", "eset", "ewait", "dld", "pld",
                    "dtrans", "dcpy", "dstr", "mmad"
                ]
            );
        }

        #[test]
        fn value_width_is_enforced() {
            let err = encode("mmad", &[("Xd", 64)]).unwrap_err();
            assert!(matches!(err, IsaError::ValueTooWide { width: 6, .. }), "{err:?}");
        }

        #[test]
        fn byte_round_trip() {
            let words = vec![0x0000_0000_0000_0053u64, 0x8000_0000_0000_0022u64];
            assert_eq!(words_from_bytes(&words_to_bytes(&words)), words);
        }
    }
}

// SPDX-License-Identifier: Apache-2.0
//
// `mlir_to_pico` — the tile-rs codegen target for the Huawei PICO NPU.
//
// # What makes this backend different
//
// Every other tile-rs target ends in a vendor compiler: `nvcc`, `hexagon-clang`,
// `ptoas`. PICO has none. Its toolchain is:
//
// ```text
//   tile_std kernel
//        |  rustc_codegen_tile
//        v
//      MLIR  --mlir_to_pico-->  .pico.s  (intrinsic program + manifest)
//                                   |
//                                   |  svp: asm_pico -> PackPicoOm
//                                   v
//                                 .om  ->  NPU
// ```
//
// So the *target language is the intrinsic set itself* — the 96 architectural
// slots modeled in [`pico_isa`] — and the "linker" is svp rebuilding an `.om`
// container around a new instruction stream.
//
// # What this emitter does and does not own
//
// It emits the **op program**: which intrinsic, on which values, at which
// shapes, with which dtype contract. It deliberately does **not** invent UB
// addresses, bank-group ids, register numbers or event barriers — on the Tier-1
// path those are owned by pypto, and a plausible-looking but wrong scaffold is
// far worse than an explicit hand-off. Values are therefore symbolic (`%t0`),
// and the manifest states the hand-off explicitly.
//
// # Honesty rules
//
// - An op with no PICO intrinsic is a hard error, never a silent stub.
// - Every emitted mnemonic must exist in [`pico_isa`]; a typo cannot survive.
// - The f32-to-f16 conversion at the DDR/UB boundary is a numeric contract and
//   is written into the manifest, not hidden.


mod machine {
    // SPDX-License-Identifier: Apache-2.0
    //
    //! Machine description for a PICO part.
    //!
    //! Two things make PICO different from every other tile-rs target, and both live
    //! here rather than being baked into the emitter:
    //!
    //! 1. **UB capacity is per-part.** The Pico tier is not the same as the larger
    //!    SVP_NNN parts, so the emitter must never assume a size. A field with no
    //!    disclosed value stays `None` and any pass that needs it fails loudly
    //!    instead of guessing.
    //! 2. **L0A / L0B / L0C are programmatic, not physical.** On the parts this
    //!    backend targets there is no separate cube-operand memory to allocate; a
    //!    cube operand is a *residency in a UB bank group*. [`L0Model`] records
    //!    which of the two worlds a part is in so the tile planner picks the right
    //!    one instead of hard-coding Ascend's L0 hierarchy.

    /// How a part exposes cube (matmul) operand storage.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum L0Model {
        /// Physically distinct L0A/L0B/L0C buffers, allocated and staged separately.
        Physical,
        /// No physical L0: cube operands are UB bank-group residencies, and the
        /// L0A/L0B/L0C names survive only as a programmatic view over UB.
        ProgrammaticOverUb,
    }

    /// A value the owner has not disclosed yet. Distinguishes "known to be absent"
    /// from "we have not been told", which the emitter must not conflate.
    pub type Disclosed<T> = Option<T>;

    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Machine {
        /// Part name, e.g. `dpicoV100`.
        pub part: String,
        /// NPU arch string handed to the svp toolchain, e.g. `V100` / `V101`.
        pub npu_arch: String,
        /// Unified-buffer capacity in bytes. `None` until disclosed — see the crate
        /// docs; no default is invented.
        pub ub_bytes: Disclosed<u32>,
        /// RAM banks in the unified buffer.
        pub ub_banks: u32,
        /// RAMs per bank group. Owner-stated 16 on the 5.6 TOPS dpico tier.
        pub bg_ram_num: u32,
        /// Minimum alignment for a vector source/destination origin, in bytes.
        pub vector_align: u32,
        /// Channel block used by the `*C16` layouts.
        pub channel_block: u32,
        pub l0: L0Model,
        /// Native vector dtype. The vector engine is FP16; f32 kernel values are
        /// converted at the DDR/UB boundary, which is a real numeric contract and
        /// is recorded in the manifest.
        pub vector_dtype: &'static str,
        /// Native cube dtype.
        pub cube_dtype: &'static str,
    }

    impl Machine {
        /// The Pico tier this backend targets.
        ///
        /// `ub_bytes` is deliberately `None`: the Pico part's UB differs from the
        /// larger SVP_NNN parts and the value is not in either open tree. Set it via
        /// [`Machine::with_ub_bytes`] once disclosed.
        pub fn pico_v100() -> Self {
            Self {
                part: "dpicoV100".into(),
                npu_arch: "V100".into(),
                ub_bytes: None,
                ub_banks: 4,
                bg_ram_num: 16,
                vector_align: 16,
                channel_block: 16,
                l0: L0Model::ProgrammaticOverUb,
                vector_dtype: "f16",
                cube_dtype: "s8",
            }
        }

        pub fn with_ub_bytes(mut self, bytes: u32) -> Self {
            self.ub_bytes = Some(bytes);
            self
        }

        /// Bytes a tile of `elems` elements occupies in UB, honouring the alignment
        /// floor from the bank layout.
        pub fn ub_tile_bytes(&self, elems: usize, elem_bytes: usize) -> usize {
            let raw = elems * elem_bytes;
            let a = self.vector_align as usize;
            raw.div_ceil(a) * a
        }

        /// Whether a tile plan fits. `Err` names the missing disclosure rather than
        /// silently passing when capacity is unknown.
        pub fn fits_ub(&self, bytes: usize) -> Result<bool, String> {
            match self.ub_bytes {
                Some(cap) => Ok(bytes <= cap as usize),
                None => Err(format!(
                    "UB capacity for {} is not disclosed; cannot check a {bytes}-byte tile plan. \
                     Set Machine::with_ub_bytes once the owner supplies it.",
                    self.part
                )),
            }
        }
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        #[test]
        fn pico_has_no_physical_l0() {
            assert_eq!(Machine::pico_v100().l0, L0Model::ProgrammaticOverUb);
        }

        #[test]
        fn undisclosed_ub_capacity_is_an_error_not_a_guess() {
            let m = Machine::pico_v100();
            assert!(m.ub_bytes.is_none());
            let err = m.fits_ub(4096).unwrap_err();
            assert!(err.contains("not disclosed"), "{err}");
            assert_eq!(m.with_ub_bytes(8192).fits_ub(4096), Ok(true));
        }

        #[test]
        fn tiles_round_up_to_the_alignment_floor() {
            let m = Machine::pico_v100();
            assert_eq!(m.ub_tile_bytes(47, 2), 96); // 94 -> 96
            assert_eq!(m.ub_tile_bytes(8, 2), 16);
        }
    }
}

use std::collections::BTreeSet;
use std::fmt::Write as _;

pub use machine::{L0Model, Machine};

/// Tile-API operations this emitter understands.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Op {
    Load,
    Store,
    Add,
    Sub,
    Mul,
    Div,
    Max,
    Min,
    Exp,
    Log,
    Sqrt,
    Sum,
    ReduceMax,
    Rsqrt,
    Neg,
    Clamp,
    Fill,
    Transpose,
    MatmulTransposed,
    Absmax,
    /// f32 <-> f16 at the DDR/UB boundary.
    Cast,
    Quantize,
    Dequantize,
    Concat,
    Slice,
    Relu,
    Sigmoid,
    Tanh,
    Silu,
    /// `y = a * x` for a scalar `a` (`__tile_scale_`).
    Scale,
    /// `y = x + b` for a scalar `b` (`__tile_adds_`).
    AddS,
    Softmax,
    RmsNorm,
    Matmul,
}

impl Op {
    fn classify(callee: &str) -> Option<Op> {
        // Longest-first: `__tile_rms_norm_` must not be shadowed by a shorter probe.
        const TABLE: &[(&str, Op)] = &[
            ("__tile_load_", Op::Load),
            ("__tile_store_", Op::Store),
            ("__tile_rms_norm_", Op::RmsNorm),
            ("__tile_softmax_", Op::Softmax),
            ("__tile_matmul_", Op::Matmul),
            ("__tile_sigmoid_", Op::Sigmoid),
            ("__tile_tanh_", Op::Tanh),
            ("__tile_silu_", Op::Silu),
            ("__tile_relu_", Op::Relu),
            ("__tile_sqrt_", Op::Sqrt),
            ("__tile_scale_", Op::Scale),
            ("__tile_add_scalar_", Op::AddS),
            ("__tile_adds_", Op::AddS),
            ("__tile_muls_", Op::Scale),
            ("__tile_maxs_", Op::Max),
            // `__tile_reduce_max_` / `__tile_reduce_sum_` are the names tile_std
            // actually declares. An earlier table classified `__tile_rowmax_`,
            // which exists nowhere: the classifier was dead and a real
            // `__tile_reduce_max_` fell through to "no PICO intrinsic", despite
            // `vmax` being exactly that instruction.
            ("__tile_reduce_max_", Op::ReduceMax),
            ("__tile_reduce_sum_", Op::Sum),
            ("__tile_matmul_transposed_", Op::MatmulTransposed),
            ("__tile_dequantize_i8_", Op::Dequantize),
            ("__tile_quantize_", Op::Quantize),
            ("__tile_transpose_", Op::Transpose),
            ("__tile_absmax_", Op::Absmax),
            ("__tile_rsqrt_", Op::Rsqrt),
            ("__tile_clamp_", Op::Clamp),
            ("__tile_concat_", Op::Concat),
            ("__tile_slice_", Op::Slice),
            ("__tile_cast_", Op::Cast),
            ("__tile_fill_", Op::Fill),
            ("__tile_neg_", Op::Neg),
            ("__tile_sum_", Op::Sum),
            ("__tile_exp_", Op::Exp),
            ("__tile_log_", Op::Log),
            ("__tile_add_", Op::Add),
            ("__tile_sub_", Op::Sub),
            ("__tile_mul_", Op::Mul),
            ("__tile_div_", Op::Div),
            ("__tile_max_", Op::Max),
            ("__tile_min_", Op::Min),
        ];
        TABLE.iter().find(|(p, _)| callee.contains(p)).map(|(_, o)| *o)
    }

    fn name(self) -> &'static str {
        match self {
            Op::Load => "load",
            Op::Store => "store",
            Op::Add => "add",
            Op::Sub => "sub",
            Op::Mul => "mul",
            Op::Div => "div",
            Op::Max => "max",
            Op::Min => "min",
            Op::Exp => "exp",
            Op::Log => "log",
            Op::Sqrt => "sqrt",
            Op::Sum => "reduce_sum",
            Op::ReduceMax => "reduce_max",
            Op::Rsqrt => "rsqrt",
            Op::Neg => "neg",
            Op::Clamp => "clamp",
            Op::Fill => "fill",
            Op::Transpose => "transpose",
            Op::MatmulTransposed => "matmul_transposed",
            Op::Absmax => "absmax",
            Op::Cast => "cast",
            Op::Quantize => "quantize",
            Op::Dequantize => "dequantize",
            Op::Concat => "concat",
            Op::Slice => "slice",
            Op::Relu => "relu",
            Op::Sigmoid => "sigmoid",
            Op::Tanh => "tanh",
            Op::Silu => "silu",
            Op::Scale => "scale",
            Op::AddS => "adds",
            Op::Softmax => "softmax",
            Op::RmsNorm => "rms_norm",
            Op::Matmul => "matmul",
        }
    }

    /// The PICO intrinsic sequence this op lowers to.
    ///
    /// Each entry is `(mnemonic, note)`. Composite ops expand into the sequence
    /// the vector engine actually runs — there is no `softmax` instruction, so
    /// pretending there is one would hide five real instructions from the
    /// scheduler and from anyone reading the listing.
    fn lowering(self) -> &'static [(&'static str, &'static str)] {
        match self {
            Op::Load => &[("dld", "DDR -> UB")],
            Op::Store => &[("dstr", "UB -> DDR")],
            Op::Add => &[("vvadd", "elementwise")],
            Op::Sub => &[("vvsub", "elementwise")],
            Op::Mul => &[("vvmul", "elementwise")],
            Op::Div => &[("vvdiv", "elementwise")],
            Op::Max => &[("vvmax", "elementwise")],
            Op::Min => &[("vvmin", "elementwise")],
            Op::Exp => &[("vexp", "SFU")],
            Op::Log => &[("vlog", "SFU")],
            Op::Sqrt => &[("vsqrt", "SFU")],
            Op::Sum => &[("vsum", "reduction")],
            Op::ReduceMax => &[("vmax", "reduction")],
            Op::Rsqrt => &[("vsqrt", "r = sqrt(x)"), ("vdiv", "1 / r")],
            Op::Neg => &[("neg", "0 - x")],
            // The vector engine has no clamp instruction; the pair is what it
            // actually runs. `vsltc` carries a clip_en bit that may do this in
            // one word, but its field layout is unverified -- see
            // docs/OPEN-QUESTIONS.md.
            Op::Clamp => &[("vvmax", "max(x, lo)"), ("vvmin", "min(., hi)")],
            Op::Fill => &[("vsemad", "0*x + c  (the scalar multiply-add materialises a constant)")],
            // DTRANS is the UB data transform: its descriptor states the
            // structure on both sides, so a layout change is one instruction.
            Op::Transpose => &[("dtrans", "UB layout transform")],
            Op::MatmulTransposed => &[
                ("dtrans", "transpose the B operand in UB"),
                ("mmad", "cube MAC"),
            ],
            // No vector absolute value in the disclosed set, so it is built from
            // what there is: max(x, -x), then the reduction.
            Op::Absmax => &[
                ("neg", "-x"),
                ("vvmax", "|x| = max(x, -x)"),
                ("vmax", "reduction"),
            ],
            // f32 <-> f16 is not a compute instruction on PICO: the transfer
            // descriptor names the data type on each side, so the conversion
            // rides on the movement.
            Op::Cast => &[("dtrans", "in/out data type are descriptor fields, not an operation")],
            Op::Quantize => &[("vsltc", "requantise")],
            Op::Dequantize => &[("vsltc", "requantise")],
            Op::Concat => &[("dcpy", "copy into place")],
            Op::Slice => &[("dcpy", "copy the sub-view out")],
            Op::Relu => &[("vvmax", "max(x, 0) -- operand B is the zero source")],
            Op::Sigmoid => &[("vlut", "SFU nonlinearity via lookup table")],
            // The scalar multiply-add is ONE instruction on PICO, so a lone
            // scale or add-scalar still costs exactly one vsemad.
            Op::Scale => &[("vsemad", "a*x + 0")],
            Op::AddS => &[("vsemad", "1*x + b")],
            Op::Tanh => &[("vlut", "SFU nonlinearity via lookup table")],
            Op::Silu => &[
                ("vlut", "sigmoid(x)"),
                ("vvmul", "x * sigmoid(x)"),
            ],
            Op::Softmax => &[
                ("vmax", "m = rowmax(x)"),
                ("vsemad", "x - m  (scalar multiply-add, a=1 b=-m)"),
                ("vexp", "e = exp(x - m)"),
                ("vsum", "s = rowsum(e)"),
                ("vdiv", "e / s"),
            ],
            Op::RmsNorm => &[
                ("vvmul", "x * x"),
                ("vsum", "s = rowsum(x*x)"),
                ("vsemad", "s/n + eps"),
                ("vsqrt", "r = sqrt(s/n + eps)"),
                ("vdiv", "x / r"),
            ],
            Op::Matmul => &[("mmad", "cube MAC")],
        }
    }

    /// Ops that run on the cube rather than the vector engine.
    fn is_cube(self) -> bool {
        matches!(self, Op::Matmul | Op::MatmulTransposed)
    }
}

/// One parsed call in the kernel body.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Instr {
    pub op: Op,
    pub result: Option<String>,
    pub args: Vec<String>,
    /// Literal value of the f32 operand, when the op takes one (`scale`, `adds`,
    /// `rms_norm`'s eps). PICO's `vsemad` carries these as encoded immediates, so
    /// losing them here would lose the instruction's meaning.
    pub scalar: Option<String>,
}

/// A parsed kernel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Kernel {
    pub name: String,
    /// Number of `!llvm.ptr<1>` parameters — the global-memory tensors.
    pub gm_params: usize,
    pub body: Vec<Instr>,
    /// `rows`, `cols` as seen in the i32 constants feeding the tile calls.
    pub dims: Vec<i64>,
    pub eps: Option<String>,
}

fn callee_of(line: &str) -> Option<&str> {
    let at = line.find('@')?;
    let rest = &line[at + 1..];
    Some(&rest[..rest.find('(')?])
}

fn ssa_result(line: &str) -> Option<String> {
    let eq = line.find('=')?;
    let lhs = line[..eq].trim();
    lhs.starts_with('%').then(|| lhs.to_string())
}

fn call_args(line: &str) -> Vec<String> {
    let (Some(l), Some(r)) = (line.find('('), line.rfind(')')) else {
        return Vec::new();
    };
    // The trailing `: (types) -> type` clause lives after the last `)`, so the
    // arg list is the first parenthesised group after the callee.
    let inner = &line[l + 1..r];
    let inner = inner.split(')').next().unwrap_or(inner);
    inner
        .split(',')
        .map(str::trim)
        .filter(|s| s.starts_with('%'))
        .map(str::to_string)
        .collect()
}

/// Parse the subset of MLIR that `rustc_codegen_tile` hands to a target.
pub fn parse_mlir(mlir: &str) -> Result<Kernel, String> {
    let mut name = None;
    let mut gm_params = 0usize;
    let mut body = Vec::new();
    let mut consts: Vec<(String, i64)> = Vec::new();
    let mut floats: Vec<(String, String)> = Vec::new();
    let mut eps_ssa = None;

    for raw in mlir.lines() {
        let line = raw.trim();
        if line.starts_with("llvm.func") && line.contains('@') && name.is_none() {
            name = callee_of(line).map(str::to_string);
            gm_params = line.matches("!llvm.ptr<1>").count();
            continue;
        }
        if line.contains("llvm.mlir.constant") {
            if let (Some(lhs), Some(l), Some(r)) = (ssa_result(line), line.find('('), line.find(')')) {
                let inside = &line[l + 1..r];
                let lit = inside.split(':').next().unwrap_or("").trim();
                if line.contains(": i32") || line.contains(": i64") {
                    if let Ok(v) = lit.parse::<i64>() {
                        consts.push((lhs, v));
                    }
                } else if line.contains(": f32") || line.contains(": f16") {
                    floats.push((lhs, lit.to_string()));
                }
            }
            continue;
        }
        if !line.contains("llvm.call @__tile_") {
            continue;
        }
        let callee = callee_of(line).ok_or_else(|| format!("malformed call: {line}"))?;
        let op = Op::classify(callee).ok_or_else(|| {
            format!("mlir_to_pico: no PICO intrinsic lowering for `{callee}`")
        })?;
        let args = call_args(line);
        if op == Op::RmsNorm && args.len() >= 3 {
            eps_ssa = Some(args[2].clone());
        }
        let scalar = args
            .iter()
            .find_map(|a| floats.iter().find(|(n, _)| n == a).map(|(_, v)| v.clone()));
        body.push(Instr { op, result: ssa_result(line), args, scalar });
    }

    let name = name.ok_or_else(|| "mlir_to_pico: no llvm.func entry point found".to_string())?;
    if body.is_empty() {
        return Err(format!("mlir_to_pico: kernel `{name}` has no __tile_* operations"));
    }
    // Dims are the i32 constants that are not the eps value; keep them in order
    // and drop the degenerate 1s only when there is something else to keep.
    let dims: Vec<i64> = consts.iter().map(|(_, v)| *v).collect();
    let eps = eps_ssa
        .and_then(|s| floats.iter().find(|(n, _)| *n == s).map(|(_, v)| v.clone()))
        .or_else(|| body.iter().any(|i| i.op == Op::RmsNorm).then(|| "1.0e-5".to_string()));

    Ok(Kernel { name, gm_params, body, dims, eps })
}


/// One lowered operation: the source-level op (possibly a fused pair) and the
/// PICO instructions it becomes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoweredOp {
    /// Human-readable source line, e.g. `scale+adds %5 <- %3`.
    pub label: String,
    /// `(mnemonic, note)` per emitted instruction.
    pub steps: Vec<(&'static str, String)>,
    /// Source ops folded into this one (1, or 2 for a fused affine).
    pub folded: usize,
    pub unit: &'static str,
}

fn unit_of(op: Op) -> &'static str {
    if op.is_cube() {
        "cube"
    } else if matches!(op, Op::Load | Op::Store | Op::Transpose | Op::Cast | Op::Concat | Op::Slice) {
        "mte"
    } else {
        "vector"
    }
}

/// Lower a parsed body, fusing what PICO fuses.
///
/// The one fusion that matters here is **scalar affine**: `vsemad` computes
/// `a*x + b` in a single instruction, so a `scale` immediately consumed by an
/// `adds` is one instruction, not two. This is the same factoring the vendor's
/// FusedGeluTanh chain relies on — without it a lifted GELU-tanh kernel would
/// emit five `vsemad`s where the real model has three.
pub fn lower(body: &[Instr]) -> Vec<LoweredOp> {
    // A value may only be folded away if the consumer is its only user.
    let mut uses: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    for i in body {
        for a in &i.args {
            *uses.entry(a.as_str()).or_default() += 1;
        }
    }

    let mut out = Vec::new();
    let mut idx = 0;
    while idx < body.len() {
        let i = &body[idx];
        let dst = i.result.clone().unwrap_or_else(|| "_".to_string());
        let src = if i.args.is_empty() { "-".to_string() } else { i.args.join(", ") };

        let fusible = i.op == Op::Scale
            && idx + 1 < body.len()
            && body[idx + 1].op == Op::AddS
            && i.result.as_ref().is_some_and(|r| {
                body[idx + 1].args.first() == Some(r) && uses.get(r.as_str()) == Some(&1)
            });

        if fusible {
            let next = &body[idx + 1];
            let ndst = next.result.clone().unwrap_or_else(|| "_".to_string());
            let a = i.scalar.clone().unwrap_or_else(|| "a".to_string());
            let b = next.scalar.clone().unwrap_or_else(|| "b".to_string());
            out.push(LoweredOp {
                label: format!("scale+adds {ndst} <- {src}"),
                steps: vec![(
                    "vsemad",
                    format!("{a}*x + {b}  (scale and adds fused into one instruction)"),
                )],
                folded: 2,
                unit: "vector",
            });
            idx += 2;
            continue;
        }

        let steps: Vec<(&'static str, String)> = match (i.op, i.scalar.as_deref()) {
            (Op::Scale, Some(a)) => vec![("vsemad", format!("{a}*x + 0"))],
            (Op::AddS, Some(b)) => vec![("vsemad", format!("1*x + {b}"))],
            _ => i.op.lowering().iter().map(|(m, n)| (*m, (*n).to_string())).collect(),
        };
        out.push(LoweredOp {
            label: format!("{} {dst} <- {src}", i.op.name()),
            steps,
            folded: 1,
            unit: unit_of(i.op),
        });
        idx += 1;
    }
    out
}

fn json_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Build the JSON manifest svp consumes alongside the listing.
fn manifest(k: &Kernel, m: &Machine, lowered: &[LoweredOp]) -> String {
    let mut ops = Vec::new();
    for l in lowered {
        let seq: Vec<String> = l.steps.iter().map(|(s, _)| format!("\"{s}\"")).collect();
        let op = l.label.split_whitespace().next().unwrap_or("?");
        ops.push(format!(
            "    {{ \"op\": \"{}\", \"unit\": \"{}\", \"folded\": {}, \"intrinsics\": [{}] }}",
            op,
            l.unit,
            l.folded,
            seq.join(", ")
        ));
    }
    let dims: Vec<String> = k.dims.iter().map(|d| d.to_string()).collect();
    let ub = match m.ub_bytes {
        Some(b) => b.to_string(),
        None => "null".to_string(),
    };
    format!(
        r#"{{
  "abi": "pypto-pico-v1",
  "kernel": "{kernel}",
  "part": "{part}",
  "npu_arch": "{arch}",
  "gm_params": {gm},
  "dims": [{dims}],
  "eps": {eps},
  "dtype_contract": {{
    "kernel_value": "f32",
    "vector_engine": "{vdt}",
    "cube_engine": "{cdt}",
    "note": "f32 kernel values are converted at the DDR/UB boundary; the vector engine is {vdt} native."
  }},
  "l0_model": "{l0}",
  "ub_bytes": {ub},
  "ownership": {{
    "tile_rs": ["op program", "shapes", "dtype contract", "fusion groups"],
    "pypto": ["UB addressing", "bank-group allocation", "event barriers", "register allocation"],
    "svp": ["intrinsic assembly", "PackPicoOm", ".om container"]
  }},
  "ops": [
{ops}
  ]
}}"#,
        kernel = json_escape(&k.name),
        part = json_escape(&m.part),
        arch = json_escape(&m.npu_arch),
        gm = k.gm_params,
        dims = dims.join(", "),
        eps = k.eps.as_deref().map(|e| e.to_string()).unwrap_or_else(|| "null".into()),
        vdt = m.vector_dtype,
        cdt = m.cube_dtype,
        l0 = match m.l0 {
            L0Model::Physical => "physical",
            L0Model::ProgrammaticOverUb => "programmatic-over-ub",
        },
        ub = ub,
        ops = ops.join(",\n"),
    )
}

/// Multiset of intrinsic mnemonics.
pub type Histogram = std::collections::BTreeMap<&'static str, usize>;

/// Count of each PICO intrinsic a kernel lowers to.
///
/// This is the quantity that can be compared against a real `.om`: two programs
/// computing the same thing on the same engine must issue the same instruction
/// multiset, whatever the surrounding scaffold looks like.
pub fn intrinsic_histogram(mlir: &str) -> Result<Histogram, String> {
    let k = parse_mlir(mlir)?;
    let mut h = Histogram::new();
    for l in lower(&k.body) {
        for (mn, _) in l.steps {
            *h.entry(mn).or_default() += 1;
        }
    }
    Ok(h)
}

/// Lower MLIR to a PICO intrinsic program, using the default Pico machine.
///
/// This is the uniform tile-rs emitter signature — the same shape as
/// `convert_mlir_to_hexagon` and friends — so registration in
/// `tile_codegen::targets` is one line.
pub fn convert_mlir_to_pico(mlir: &str) -> Result<String, String> {
    convert_mlir_to_pico_for(mlir, &Machine::pico_v100())
}

/// Lower MLIR for a specific part.
pub fn convert_mlir_to_pico_for(mlir: &str, m: &Machine) -> Result<String, String> {
    if mlir.trim().is_empty() {
        return Err("mlir_to_pico: empty MLIR module".to_string());
    }
    let k = parse_mlir(mlir)?;
    let lowered = lower(&k.body);

    // Every mnemonic we are about to print must be a real intrinsic. This is the
    // check that makes the listing trustworthy rather than suggestive.
    let mut used: BTreeSet<&'static str> = BTreeSet::new();
    for l in &lowered {
        for (mn, _) in &l.steps {
            let intr = pico_isa::by_name(mn).ok_or_else(|| {
                format!("mlir_to_pico: `{mn}` is not a PICO intrinsic (lowering `{}`)", l.label)
            })?;
            debug_assert!(intr.name == Some(*mn));
            used.insert(mn);
        }
    }

    let mut out = String::new();
    let _ = writeln!(out, "; Generated by tile-rs mlir_to_pico -- DO NOT EDIT");
    let _ = writeln!(out, "; target : PICO / SVP_NNN ({}), 7-bit opcode, 8-byte word", m.part);
    let _ = writeln!(out, "; build  : svp assembles this listing -- asm_pico -> PackPicoOm -> .om");
    let _ = writeln!(out, ";          there is no ptoas on this path.");
    let _ = writeln!(out, ";");
    let _ = writeln!(out, "; Values are SYMBOLIC. UB addressing, bank groups, events and register");
    let _ = writeln!(out, "; allocation are resolved by pypto; this listing states the op program only.");
    let _ = writeln!(out, ";");
    let _ = writeln!(out, "; @manifest");
    for line in manifest(&k, m, &lowered).lines() {
        let _ = writeln!(out, "; {line}");
    }
    let _ = writeln!(out, "; @end-manifest");
    let _ = writeln!(out);

    let _ = writeln!(out, ".kernel {}", k.name);
    let _ = writeln!(out, ".part   {} ({})", m.part, m.npu_arch);
    let _ = writeln!(
        out,
        ".dtype  kernel=f32 vector={} cube={}   ; converted at the DDR/UB boundary",
        m.vector_dtype, m.cube_dtype
    );
    match m.l0 {
        L0Model::ProgrammaticOverUb => {
            let _ = writeln!(
                out,
                ".l0     programmatic-over-ub          ; no physical L0A/L0B/L0C; cube operands are UB bank-group residencies"
            );
        }
        L0Model::Physical => {
            let _ = writeln!(out, ".l0     physical");
        }
    }
    match m.ub_bytes {
        Some(b) => {
            let _ = writeln!(out, ".ub     {b} bytes, {} banks, bg_ram_num={}", m.ub_banks, m.bg_ram_num);
        }
        None => {
            let _ = writeln!(
                out,
                ".ub     <undisclosed> bytes, {} banks, bg_ram_num={}   ; capacity not disclosed for this part",
                m.ub_banks, m.bg_ram_num
            );
        }
    }
    let _ = writeln!(out, ".gm     {} tensors", k.gm_params);
    let _ = writeln!(out);

    for (idx, l) in lowered.iter().enumerate() {
        let _ = writeln!(out, "  ; [{idx}] {}", l.label);
        for (mn, note) in &l.steps {
            let intr = pico_isa::by_name(mn).expect("checked above");
            let status = match intr.status {
                pico_isa::Status::FieldsVerified => "",
                pico_isa::Status::FieldsInferred => "   [layout inferred]",
                pico_isa::Status::NameOnly => "   [fields TBD]",
                pico_isa::Status::Unassigned => "   [unassigned]",
            };
            let _ = writeln!(out, "  {:<8} ; op=0x{:02x}  {note}{status}", mn, intr.op);
        }
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "  end      ; op=0x{:02x}", pico_isa::by_name("end").expect("end").op);
    let _ = writeln!(out);
    let _ = writeln!(out, "; intrinsics used: {}", used.iter().copied().collect::<Vec<_>>().join(" "));

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn softmax_mlir() -> &'static str {
        r#"
module {
  llvm.func @tile_softmax(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %1 = llvm.mlir.constant(1 : i32) : i32
    %2 = llvm.mlir.constant(1024 : i32) : i32
    %3 = llvm.call @__tile_load_f32(%arg0, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %4 = llvm.call @__tile_softmax_f32(%3, %3, %1, %2) : (i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg1, %4, %1, %2) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#
    }

    fn silu_mul_mlir() -> &'static str {
        r#"
module {
  llvm.func @gated_mlp(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>, %arg2: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %1 = llvm.mlir.constant(1 : i32) : i32
    %2 = llvm.mlir.constant(8960 : i32) : i32
    %3 = llvm.call @__tile_load_f32(%arg0, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %4 = llvm.call @__tile_load_f32(%arg1, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %5 = llvm.call @__tile_silu_f32(%3, %3, %1, %2) : (i32, i32, i32, i32) -> i32
    %6 = llvm.call @__tile_mul_f32(%5, %4, %1, %2) : (i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg2, %6, %1, %2) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#
    }

    fn rms_norm_mlir() -> &'static str {
        r#"
module {
  llvm.func @tile_rms_norm(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %1 = llvm.mlir.constant(1 : i32) : i32
    %2 = llvm.mlir.constant(1536 : i32) : i32
    %eps = llvm.mlir.constant(1.0e-6 : f32) : f32
    %3 = llvm.call @__tile_load_f32(%arg0, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %4 = llvm.call @__tile_rms_norm_f32(%3, %3, %eps, %1, %2) : (i32, i32, f32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg1, %4, %1, %2) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#
    }

    #[test]
    fn parses_the_kernel_shape() {
        let k = parse_mlir(softmax_mlir()).unwrap();
        assert_eq!(k.name, "tile_softmax");
        assert_eq!(k.gm_params, 2);
        assert_eq!(k.body.len(), 3);
        assert_eq!(k.body[1].op, Op::Softmax);
        assert_eq!(k.dims, vec![1, 1024]);
    }

    #[test]
    fn softmax_expands_into_the_five_real_instructions() {
        let s = convert_mlir_to_pico(softmax_mlir()).unwrap();
        for mn in ["vmax", "vsemad", "vexp", "vsum", "vdiv"] {
            assert!(s.contains(mn), "softmax lowering must show `{mn}`:\n{s}");
        }
        assert!(s.contains("dld"), "load must lower to dld:\n{s}");
        assert!(s.contains("dstr"), "store must lower to dstr:\n{s}");
        assert!(s.contains("PackPicoOm"), "the build path must name svp's packer:\n{s}");
    }

    #[test]
    fn every_emitted_mnemonic_is_a_real_intrinsic() {
        for src in [softmax_mlir(), silu_mul_mlir(), rms_norm_mlir()] {
            let listing = convert_mlir_to_pico(src).unwrap();
            let used = listing
                .lines()
                .find_map(|l| l.strip_prefix("; intrinsics used: "))
                .expect("used-intrinsics footer");
            for mn in used.split_whitespace() {
                assert!(pico_isa::by_name(mn).is_some(), "`{mn}` is not a PICO intrinsic");
            }
        }
    }

    #[test]
    fn silu_lowers_to_lut_then_multiply() {
        let s = convert_mlir_to_pico(silu_mul_mlir()).unwrap();
        let lut = s.find("vlut").expect("vlut");
        let mul = s.rfind("vvmul").expect("vvmul");
        assert!(lut < mul, "sigmoid must precede the multiply:\n{s}");
    }

    #[test]
    fn rms_norm_carries_its_eps_into_the_manifest() {
        let s = convert_mlir_to_pico(rms_norm_mlir()).unwrap();
        assert!(s.contains("\"eps\": 1.0e-6"), "eps must reach the manifest:\n{s}");
    }

    #[test]
    fn the_manifest_states_who_owns_the_scaffold() {
        let s = convert_mlir_to_pico(softmax_mlir()).unwrap();
        assert!(s.contains("\"pypto\": [\"UB addressing\""), "{s}");
        assert!(s.contains("programmatic-over-ub"), "L0 model must be explicit:\n{s}");
        assert!(s.contains("\"ub_bytes\": null"), "undisclosed UB must stay null:\n{s}");
    }

    #[test]
    fn an_unknown_tile_op_is_an_error_not_a_stub() {
        let bad = r#"
module {
  llvm.func @k(%arg0: !llvm.ptr<1>) attributes {hacc.entry} {
    %1 = llvm.call @__tile_conv3d_f32(%arg0) : (!llvm.ptr<1>) -> i32
    llvm.return
  }
}
"#;
        let err = convert_mlir_to_pico(bad).unwrap_err();
        assert!(err.contains("no PICO intrinsic lowering"), "{err}");
    }

    #[test]
    fn empty_and_bodyless_modules_are_errors() {
        assert!(convert_mlir_to_pico("").is_err());
        assert!(convert_mlir_to_pico("module { llvm.func @k() { llvm.return } }").is_err());
    }

    #[test]
    fn a_scale_consumed_by_an_adds_becomes_one_vsemad() {
        // vsemad is a*x + b in a single instruction. Two source ops, one word.
        let mlir = r#"
module {
  llvm.func @affine(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    %1 = llvm.mlir.constant(1 : i32) : i32
    %2 = llvm.mlir.constant(40 : i32) : i32
    %3 = llvm.call @__tile_load_f32(%arg0, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %4 = llvm.call @__tile_scale_f32(%3, %1, %2) : (i32, i32, i32) -> i32
    %5 = llvm.call @__tile_adds_f32(%4, %1, %2) : (i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg1, %5, %1, %2) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let h = intrinsic_histogram(mlir).unwrap();
        assert_eq!(h.get("vsemad"), Some(&1), "scale+adds must fuse: {h:?}");
        let s = convert_mlir_to_pico(mlir).unwrap();
        assert!(s.contains("scale+adds"), "the fusion must be visible in the listing:\n{s}");
    }

    #[test]
    fn a_scale_with_two_consumers_is_not_folded_away() {
        // Folding would delete a value the second consumer still needs.
        let mlir = r#"
module {
  llvm.func @k(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    %1 = llvm.mlir.constant(1 : i32) : i32
    %2 = llvm.mlir.constant(40 : i32) : i32
    %3 = llvm.call @__tile_load_f32(%arg0, %1, %2) : (!llvm.ptr<1>, i32, i32) -> i32
    %4 = llvm.call @__tile_scale_f32(%3, %1, %2) : (i32, i32, i32) -> i32
    %5 = llvm.call @__tile_adds_f32(%4, %1, %2) : (i32, i32, i32) -> i32
    %6 = llvm.call @__tile_mul_f32(%4, %5, %1, %2) : (i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg1, %6, %1, %2) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let h = intrinsic_histogram(mlir).unwrap();
        assert_eq!(h.get("vsemad"), Some(&2), "two live uses, two instructions: {h:?}");
    }

    #[test]
    fn a_part_with_disclosed_ub_reports_it() {
        let m = Machine::pico_v100().with_ub_bytes(512 * 1024);
        let s = convert_mlir_to_pico_for(softmax_mlir(), &m).unwrap();
        assert!(s.contains("\"ub_bytes\": 524288"), "{s}");
        assert!(s.contains(".ub     524288 bytes"), "{s}");
    }
}
