// SPDX-License-Identifier: Apache-2.0
//
//! `mlir_to_rvv` — RISC-V Vector (RVV 1.0) emitter, via the linalg bridge.
//!
//! # Target
//! Any RVA23-class core with the `V` extension: SiFive Intelligence X-series,
//! Alibaba XuanTie C9xx, Ventana Veyron, SpacemiT K1/M1, and the cheap dev
//! boards (Milk-V, Banana Pi F3) that make bring-up possible without vendor
//! silicon.
//!
//! # Why this backend has no translator of its own
//! Every other vendor backend emits *that vendor's* source language, because
//! there is no other way in: AscendC, TPC-C, NKI and MSL each have a bespoke
//! compiler. RISC-V does not have that problem — LLVM already owns RVV codegen
//! upstream. So the shortest correct path is to hand LLVM well-formed
//! `linalg`-on-tensors and let the standard MLIR pipeline lower it.
//!
//! This emitter is therefore a thin wrapper over [`convert_mlir_to_linalg`]:
//! it takes the neutral linalg egress and makes it a *RISC-V* artifact by
//! attaching the target triple and data layout, so `mlir-translate` stamps the
//! right module header and `llc` needs no extra flags to agree with it.
//!
//! # The lowering it is meant to feed
//! `scripts/rvv_lower.sh` drives the pipeline this file documents. Both were
//! validated against LLVM 20 (the version the codegen backend already pins) —
//! elementwise, matmul and softmax all reach real RVV instructions
//! (`vle32.v` / `vfadd.vv` / `vfmul.vv` / `vse32.v`).
//!
//! # Two findings worth keeping in the header
//! 1. **`llc` autovectorisation is not enough.** Lowering straight through
//!    `-convert-linalg-to-affine-loops` and leaving vectorisation to `opt -O3`
//!    / `llc -mattr=+v` produces a *fully scalar* loop (`flw` / `fadd.s` /
//!    `fsw`) — the loop vectoriser does not fire on the pointer arithmetic that
//!    survives `finalize-memref-to-llvm`. Vectorisation has to happen at the
//!    MLIR level, via `-affine-super-vectorize`, before the memref lowering.
//! 2. **`linalg.softmax` does not lower in stock LLVM 20.** It is a named op
//!    carrying `DecomposeInterface`, and no `mlir-opt` *pass* applies it — it
//!    needs the transform dialect. `scripts/rvv_decompose.mlir` holds that
//!    schedule and is preloaded, so the emitted payload stays a clean linalg
//!    module with no transform ops inside it.

use crate::mlir_to_linalg::convert_mlir_to_linalg;

/// LLVM target triple stamped on the emitted module. Matches the `-mtriple`
/// that `scripts/rvv_lower.sh` passes to `llc`.
pub const RVV_TRIPLE: &str = "riscv64-unknown-linux-gnu";

/// Data layout for rv64gcv (LP64D). Kept beside the triple so `mlir-translate`
/// emits a module header `llc` does not have to be argued out of.
pub const RVV_DATA_LAYOUT: &str = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128";

/// Convert MLIR text (merged module, LLVM dialect) into a RISC-V-targeted
/// `linalg`-on-tensors module.
///
/// Pure: no filesystem, no environment, no toolchain — same contract as every
/// other `convert_mlir_to_*`.
pub fn convert_mlir_to_rvv(mlir_text: &str) -> Result<String, String> {
    let linalg = convert_mlir_to_linalg(mlir_text)?;
    Ok(wrap_for_riscv(&linalg))
}

/// Wrap the bare `func.func`s the linalg bridge emits in a `module` carrying the
/// RISC-V triple + data layout, and prepend the lowering recipe.
///
/// `convert_mlir_to_linalg` emits a comment banner followed by top-level
/// `func.func` ops with no enclosing `module`, so the wrapping is ours to do.
fn wrap_for_riscv(linalg: &str) -> String {
    let mut out = String::with_capacity(linalg.len() + 2048);

    out.push_str("// Generated by tile-rs mlir_to_rvv — DO NOT EDIT\n");
    out.push_str("// Target: RISC-V rv64gcv (RVV 1.0), via the linalg bridge.\n");
    out.push_str("//\n");
    out.push_str("// Lower with:  scripts/rvv_lower.sh <this_file> -o kernel.s\n");
    out.push_str("//\n");
    out.push_str("// which runs, in order:\n");
    out.push_str("//   mlir-opt -transform-preload-library=\\\n");
    out.push_str("//              transform-library-paths=scripts/rvv_decompose.mlir \\\n");
    out.push_str("//            -transform-interpreter \\\n");
    out.push_str("//            -linalg-generalize-named-ops \\\n");
    out.push_str("//            -one-shot-bufferize=bufferize-function-boundaries \\\n");
    out.push_str("//            -convert-linalg-to-affine-loops \\\n");
    out.push_str("//            -affine-super-vectorize=virtual-vector-size=<VL> \\\n");
    out.push_str("//            -lower-affine -convert-scf-to-cf -convert-vector-to-llvm \\\n");
    out.push_str("//            -convert-math-to-llvm -convert-math-to-libm ...\n");
    out.push_str("//   mlir-translate --mlir-to-llvmir\n");
    out.push_str("//   opt -O3\n");
    out.push_str("//   llc -mtriple=riscv64 -mattr=+v,+zvl128b,+d\n");
    out.push_str("//\n");
    out.push_str("// NOTE: -affine-super-vectorize is load-bearing. Without it the loop\n");
    out.push_str("// vectoriser does not fire on the lowered memrefs and llc emits scalar\n");
    out.push_str("// flw/fadd.s/fsw — correct, and roughly VLEN/32 times too slow.\n");
    out.push('\n');

    out.push_str("module attributes {\n");
    out.push_str(&format!("  llvm.target_triple = \"{RVV_TRIPLE}\",\n"));
    out.push_str(&format!("  llvm.data_layout = \"{RVV_DATA_LAYOUT}\"\n"));
    out.push_str("} {\n");

    // Indent the linalg body one level, dropping its own generated banner —
    // ours already says where the file came from.
    for line in linalg.lines() {
        let t = line.trim_start();
        if t.starts_with("// Generated by tile-rs mlir_to_linalg")
            || t.starts_with("// Verify: mlir-opt")
        {
            continue;
        }
        if line.trim().is_empty() {
            out.push('\n');
        } else {
            out.push_str("  ");
            out.push_str(line);
            out.push('\n');
        }
    }

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    // Canonical snippet, matching the shape the shared `mlir_parse` expects
    // (`hacc.entry`, addrspace-1 pointers, `(ptr, rows, cols)` intrinsics) —
    // same text the linalg emitter's own tests use.
    const ADD: &str = r#"
module {
  llvm.func @tile_add(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>, %arg2: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %a = llvm.call @__tile_load_f32(%arg0, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %b = llvm.call @__tile_load_f32(%arg1, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @__tile_add_f32(%a, %a, %b, %r, %c) : (i32, i32, i32, i32, i32) -> i32
    llvm.call @__tile_store_f32(%arg2, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;

    #[test]
    fn emits_riscv_target_triple() {
        let out = convert_mlir_to_rvv(ADD).expect("emit");
        assert!(out.contains("riscv64"), "must carry the RISC-V triple");
        assert!(out.contains("llvm.target_triple"));
        assert!(out.contains("llvm.data_layout"));
    }

    #[test]
    fn wraps_linalg_in_a_module() {
        let out = convert_mlir_to_rvv(ADD).expect("emit");
        assert!(out.contains("module attributes {"));
        assert!(out.contains("linalg."), "linalg payload must survive");
        assert!(out.trim_end().ends_with('}'), "module must be closed");
    }

    #[test]
    fn payload_carries_no_transform_ops() {
        // The decomposition schedule is preloaded from a separate library file,
        // never inlined — a payload containing transform ops fails
        // `mlir-translate --mlir-to-llvmir` at the end of the pipeline.
        let out = convert_mlir_to_rvv(ADD).expect("emit");
        assert!(!out.contains("transform.named_sequence"));
        assert!(!out.contains("transform.with_named_sequence"));
    }

    #[test]
    fn documents_the_vectorisation_requirement() {
        // Finding (1) in the module header: dropping -affine-super-vectorize
        // silently yields scalar code. Keep the warning attached to the artifact.
        let out = convert_mlir_to_rvv(ADD).expect("emit");
        assert!(out.contains("affine-super-vectorize"));
    }

    #[test]
    fn does_not_duplicate_the_linalg_banner() {
        let out = convert_mlir_to_rvv(ADD).expect("emit");
        assert!(!out.contains("mlir_to_linalg — DO NOT EDIT"));
        assert_eq!(out.matches("DO NOT EDIT").count(), 1);
    }

    #[test]
    fn is_deterministic() {
        let a = convert_mlir_to_rvv(ADD).expect("emit");
        let b = convert_mlir_to_rvv(ADD).expect("emit");
        assert_eq!(a, b, "emit must be a pure function of its input");
    }

    #[test]
    fn empty_module_is_an_error() {
        assert!(convert_mlir_to_rvv("").is_err());
    }
}
