// SPDX-License-Identifier: Apache-2.0
//
//! `mlir_to_ttmetal` — Tenstorrent TT-Metal compute-kernel emitter.
//!
//! # Target
//! - Tenstorrent Wormhole / Blackhole boards via the TT-Metal SDK.
//! - Compute kernels live on each Tensix core; the TT-Metal host runtime
//!   loads them via `CreateKernel(…, {.compile_args = {…}})` and launches
//!   with `EnqueueProgram`.
//! - Kernel source gets compiled by TT-Metal's internal Clang-based
//!   toolchain (`tt-metal/tt_metal/hw/toolchain/…`).
//!
//! # Scope of this first version
//! The emitter produces a minimal TT-Metal *compute* kernel (one `MAIN`
//! block per function) that covers the same 5 Table-2 kernels we emit
//! for Gaudi/BANG/MUSA: softmax, rms_norm, add, exp, matmul. Each kernel:
//!
//! 1. Waits for input circular buffers via `cb_wait_front`.
//! 2. Runs a tile-level compute op from `compute_kernel_api/*`.
//! 3. Publishes the output via `cb_push_back`.
//!
//! For host-side runtime wiring (CB allocation, NOC DMA, kernel launch)
//! see `benchmarks/tenstorrent/bench_ascendrs_ttmetal.py` — this emitter
//! only produces the `.cpp` compute-kernel source.
//!
//! # Intrinsic mapping (tile-level, 32x32 FP16 tiles)
//! | tile-rs intrinsic            | TT-Metal compute API                                  |
//! |--------------------------------|-------------------------------------------------------|
//! | `ascend_tile_load_f32`         | `cb_wait_front(cb_in, 1)` + `copy_tile_init(cb_in)`   |
//! | `ascend_tile_store_f32`        | `pack_tile(0, cb_out)` + `cb_push_back(cb_out, 1)`    |
//! | `ascend_tile_add_f32`          | `add_tiles(cb_a, cb_b, 0, 0, 0)`                      |
//! | `ascend_tile_exp_f32`          | `exp_tile_init()` + `exp_tile(0)`                     |
//! | `ascend_tile_softmax_f32`      | `softmax_tile_init()` + `softmax_tile(0)`             |
//! | `ascend_tile_rms_norm_f32`     | `rms_norm_tile_init(eps)` + `rms_norm_tile(0)`        |
//! | `ascend_tile_matmul_f32`       | `mm_init(cb_a, cb_b, cb_out)` + `matmul_tiles(...)`   |
//!
//! The tile size (32x32 FP16 = 2048 bytes) is fixed by the Tensix
//! architecture, so the emitter ignores `rows`/`cols` for tile-granular
//! ops and tiles the work on the host side instead.
//!
//! # Example output
//! ```cpp
//! // Generated by tile-rs mlir_to_ttmetal — DO NOT EDIT
//! // Compile: tt-metal kernel compile via CreateKernel(…, TENSIX).
//! #include "compute_kernel_api/common.h"
//! #include "compute_kernel_api/softmax.h"
//! namespace NAMESPACE {
//! void MAIN {
//!     constexpr auto cb_in  = tt::CB::c_in0;
//!     constexpr auto cb_out = tt::CB::c_out0;
//!     softmax_tile_init();
//!     cb_wait_front(cb_in, 1);
//!     cb_reserve_back(cb_out, 1);
//!     acquire_dst(tt::DstMode::Half);
//!     copy_tile(cb_in, 0, 0);
//!     softmax_tile(0);
//!     pack_tile(0, cb_out);
//!     release_dst(tt::DstMode::Half);
//!     cb_pop_front(cb_in, 1);
//!     cb_push_back(cb_out, 1);
//! }
//! }  // namespace NAMESPACE
//! ```
//!
//! Run under `benchmarks/tenstorrent/bench_ascendrs_ttmetal.py` on a
//! rented Tenstorrent Cloud instance — compile-only Tier 1 today, device
//! run Tier 2 is tracked as TODO.

use std::collections::HashMap;

#[derive(Debug, Clone, Copy, PartialEq)]
enum Op {
    Load,
    Store,
    Add,
    Exp,
    Softmax,
    RmsNorm,
    Matmul,
    Unknown,
}

fn classify_callee(callee: &str) -> Op {
    if callee.contains("ascend_tile_load_") {
        Op::Load
    } else if callee.contains("ascend_tile_store_") {
        Op::Store
    } else if callee.contains("ascend_tile_add_") {
        Op::Add
    } else if callee.contains("ascend_tile_exp_") {
        Op::Exp
    } else if callee.contains("ascend_tile_softmax_") {
        Op::Softmax
    } else if callee.contains("ascend_tile_rms_norm_") {
        Op::RmsNorm
    } else if callee.contains("ascend_tile_matmul_") {
        Op::Matmul
    } else {
        Op::Unknown
    }
}

fn extract_call_callee(line: &str) -> Option<&str> {
    let at = line.find('@')?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(&rest[..end])
}

fn extract_fn_name(line: &str) -> Option<String> {
    let at = line.find("@")?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(rest[..end].to_string())
}

fn required_headers(ops: &[Op]) -> Vec<&'static str> {
    let mut hs: Vec<&'static str> = vec!["compute_kernel_api/common.h"];
    let mut seen: HashMap<&'static str, ()> = HashMap::new();
    for op in ops {
        let h = match op {
            Op::Add => "compute_kernel_api/eltwise_binary.h",
            Op::Exp => "compute_kernel_api/eltwise_unary/exp.h",
            Op::Softmax => "compute_kernel_api/softmax.h",
            Op::RmsNorm => "compute_kernel_api/rms_norm.h",
            Op::Matmul => "compute_kernel_api/matmul.h",
            _ => continue,
        };
        if seen.insert(h, ()).is_none() {
            hs.push(h);
        }
    }
    hs
}

fn emit_init(op: Op, out: &mut String) {
    match op {
        Op::Add => out.push_str("    binary_op_init_common(cb_in0, cb_in1, cb_out);\n"),
        Op::Exp => out.push_str("    init_sfpu(cb_in0, cb_out);\n    exp_tile_init();\n"),
        Op::Softmax => {
            out.push_str("    init_sfpu(cb_in0, cb_out);\n    softmax_tile_init();\n");
        }
        Op::RmsNorm => {
            out.push_str("    init_sfpu(cb_in0, cb_out);\n    rms_norm_tile_init();\n");
        }
        Op::Matmul => out.push_str("    mm_init(cb_in0, cb_in1, cb_out);\n"),
        _ => {}
    }
}

fn emit_body(op: Op, out: &mut String) {
    match op {
        Op::Add => {
            out.push_str("    cb_wait_front(cb_in0, 1);\n");
            out.push_str("    cb_wait_front(cb_in1, 1);\n");
            out.push_str("    cb_reserve_back(cb_out, 1);\n");
            out.push_str("    acquire_dst();\n");
            out.push_str("    add_tiles(cb_in0, cb_in1, 0, 0, 0);\n");
            out.push_str("    pack_tile(0, cb_out);\n");
            out.push_str("    release_dst();\n");
            out.push_str("    cb_pop_front(cb_in0, 1);\n");
            out.push_str("    cb_pop_front(cb_in1, 1);\n");
            out.push_str("    cb_push_back(cb_out, 1);\n");
        }
        Op::Exp => {
            out.push_str("    cb_wait_front(cb_in0, 1);\n");
            out.push_str("    cb_reserve_back(cb_out, 1);\n");
            out.push_str("    acquire_dst();\n");
            out.push_str("    copy_tile(cb_in0, 0, 0);\n");
            out.push_str("    exp_tile(0);\n");
            out.push_str("    pack_tile(0, cb_out);\n");
            out.push_str("    release_dst();\n");
            out.push_str("    cb_pop_front(cb_in0, 1);\n");
            out.push_str("    cb_push_back(cb_out, 1);\n");
        }
        Op::Softmax => {
            out.push_str("    cb_wait_front(cb_in0, 1);\n");
            out.push_str("    cb_reserve_back(cb_out, 1);\n");
            out.push_str("    acquire_dst();\n");
            out.push_str("    copy_tile(cb_in0, 0, 0);\n");
            out.push_str("    softmax_tile(0);\n");
            out.push_str("    pack_tile(0, cb_out);\n");
            out.push_str("    release_dst();\n");
            out.push_str("    cb_pop_front(cb_in0, 1);\n");
            out.push_str("    cb_push_back(cb_out, 1);\n");
        }
        Op::RmsNorm => {
            out.push_str("    cb_wait_front(cb_in0, 1);\n");
            out.push_str("    cb_reserve_back(cb_out, 1);\n");
            out.push_str("    acquire_dst();\n");
            out.push_str("    copy_tile(cb_in0, 0, 0);\n");
            out.push_str("    rms_norm_tile(0);\n");
            out.push_str("    pack_tile(0, cb_out);\n");
            out.push_str("    release_dst();\n");
            out.push_str("    cb_pop_front(cb_in0, 1);\n");
            out.push_str("    cb_push_back(cb_out, 1);\n");
        }
        Op::Matmul => {
            out.push_str("    cb_wait_front(cb_in0, 1);\n");
            out.push_str("    cb_wait_front(cb_in1, 1);\n");
            out.push_str("    cb_reserve_back(cb_out, 1);\n");
            out.push_str("    acquire_dst();\n");
            out.push_str("    matmul_tiles(cb_in0, cb_in1, 0, 0, 0, false);\n");
            out.push_str("    pack_tile(0, cb_out);\n");
            out.push_str("    release_dst();\n");
            out.push_str("    cb_pop_front(cb_in0, 1);\n");
            out.push_str("    cb_pop_front(cb_in1, 1);\n");
            out.push_str("    cb_push_back(cb_out, 1);\n");
        }
        _ => {}
    }
}

/// Convert MLIR with `ascend_tile_*` intrinsics into a TT-Metal compute kernel.
pub fn convert_mlir_to_ttmetal(mlir_text: &str) -> Result<String, String> {
    // Find the kernel function name and scan its body for tile ops.
    let mut fn_name: Option<String> = None;
    let mut ops: Vec<Op> = Vec::new();
    for raw in mlir_text.lines() {
        let line = raw.trim();
        if line.starts_with("llvm.func @") {
            fn_name = extract_fn_name(line);
        }
        if line.contains("llvm.call @ascend_tile_") {
            if let Some(callee) = extract_call_callee(line) {
                let op = classify_callee(callee);
                if op != Op::Unknown && op != Op::Load && op != Op::Store {
                    ops.push(op);
                }
            }
        }
    }
    let fn_name = fn_name.unwrap_or_else(|| "tile_kernel".to_string());

    let mut out = String::new();
    out.push_str("// Generated by tile-rs mlir_to_ttmetal — DO NOT EDIT\n");
    out.push_str("// Compile: loaded via TT-Metal CreateKernel(..., TENSIX) on Wormhole/Blackhole.\n");
    out.push_str("//\n");
    out.push_str("// Circular-buffer layout (matches host-side ascendrs_ttmetal launcher):\n");
    out.push_str("//   cb_in0  = tt::CB::c_in0   (GM input 0)\n");
    out.push_str("//   cb_in1  = tt::CB::c_in1   (GM input 1, unused for unary ops)\n");
    out.push_str("//   cb_out  = tt::CB::c_out0  (GM output)\n");
    out.push_str("\n");
    for h in required_headers(&ops) {
        out.push_str(&format!("#include \"{}\"\n", h));
    }
    out.push_str("\nnamespace NAMESPACE {\n");
    out.push_str(&format!("// kernel: {}\n", fn_name));
    out.push_str("void MAIN {\n");
    out.push_str("    constexpr auto cb_in0 = tt::CB::c_in0;\n");
    out.push_str("    constexpr auto cb_in1 = tt::CB::c_in1;\n");
    out.push_str("    constexpr auto cb_out = tt::CB::c_out0;\n\n");

    // Init calls (must precede per-tile compute).
    for op in &ops {
        emit_init(*op, &mut out);
    }
    out.push_str("\n");

    // Per-tile compute body.
    for op in &ops {
        emit_body(*op, &mut out);
    }

    out.push_str("}\n");
    out.push_str("}  // namespace NAMESPACE\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_ttmetal_header() {
        let mlir = r#"
module {
  llvm.func @tile_exp(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %x = llvm.call @ascend_tile_load_f32(%arg0, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_exp_f32(%x, %x, %r, %c) : (i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%arg1, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let cpp = convert_mlir_to_ttmetal(mlir).unwrap();
        assert!(cpp.contains("namespace NAMESPACE"));
        assert!(cpp.contains("void MAIN"));
        assert!(cpp.contains("compute_kernel_api/eltwise_unary/exp.h"));
        assert!(cpp.contains("exp_tile_init"));
        assert!(cpp.contains("exp_tile(0)"));
    }

    #[test]
    fn test_ttmetal_matmul() {
        let mlir = r#"
module {
  llvm.func @tile_matmul(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>, %c: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %m = llvm.mlir.constant(128 : i32) : i32
    %k = llvm.mlir.constant(128 : i32) : i32
    %n = llvm.mlir.constant(128 : i32) : i32
    %al = llvm.call @ascend_tile_load_f32(%a, %m, %k) : (!llvm.ptr<1>, i32, i32) -> i32
    %bl = llvm.call @ascend_tile_load_f32(%b, %k, %n) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_matmul_f32(%al, %al, %bl, %m, %k, %n) : (i32, i32, i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%c, %y, %m, %n) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let cpp = convert_mlir_to_ttmetal(mlir).unwrap();
        assert!(cpp.contains("compute_kernel_api/matmul.h"));
        assert!(cpp.contains("mm_init(cb_in0, cb_in1, cb_out)"));
        assert!(cpp.contains("matmul_tiles(cb_in0, cb_in1, 0, 0, 0, false)"));
    }

    #[test]
    fn test_ttmetal_softmax() {
        let mlir = r#"
module {
  llvm.func @tile_softmax(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %x = llvm.call @ascend_tile_load_f32(%a, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_softmax_f32(%x, %x, %r, %c) : (i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%b, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let cpp = convert_mlir_to_ttmetal(mlir).unwrap();
        assert!(cpp.contains("softmax_tile_init"));
        assert!(cpp.contains("softmax_tile(0)"));
    }

    #[test]
    fn test_ttmetal_rms_norm() {
        let mlir = r#"
module {
  llvm.func @tile_rms(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %eps = llvm.mlir.constant(1.0e-5 : f32) : f32
    %x = llvm.call @ascend_tile_load_f32(%a, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_rms_norm_f32(%x, %x, %eps, %r, %c) : (i32, i32, f32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%b, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let cpp = convert_mlir_to_ttmetal(mlir).unwrap();
        assert!(cpp.contains("rms_norm_tile_init"));
        assert!(cpp.contains("rms_norm_tile(0)"));
    }
}
