// SPDX-License-Identifier: Apache-2.0
//
//! `mlir_to_csl` — Cerebras WSE CSL emitter.
//!
//! # Target
//! - Cerebras CS-2 / CS-3 Wafer-Scale Engines via the CSL SDK.
//! - Programs are split into a **layout** file (`.csl`) that maps code to
//!   the PE fabric and **kernel** files (`.csl`) that each PE runs.
//! - Compilation: `cslc --arch=wse2 --fabric-dims=<N>,<M> <layout>.csl`
//!   emits an ELF per PE and a launcher.
//!
//! # Scope of this first version
//! One-PE kernel skeletons for the 5 Table-2 ops: softmax, rms_norm,
//! add, exp, matmul. Each file declares a single task that reads an input
//! tile from a color/fabric import, runs a compute pass, and writes to an
//! output import. Host-side fabric layout, memcpy streaming, and per-PE
//! tiling are out-of-scope — they live in `benchmarks/cerebras/bench_…`.
//!
//! # Intrinsic mapping (per-PE, float32 arrays of length N)
//! | tile-rs intrinsic          | CSL construct                                           |
//! |------------------------------|---------------------------------------------------------|
//! | `ascend_tile_load_f32`       | `input_tile: [N]f32` imported from a fabric color       |
//! | `ascend_tile_store_f32`      | assigned to `output_tile: [N]f32` (exported)            |
//! | `ascend_tile_add_f32`        | `@math.add(&out, &a, &b);`                              |
//! | `ascend_tile_exp_f32`        | `@math.exp(&out, &x);`                                  |
//! | `ascend_tile_softmax_f32`    | inline: max → sub → exp → sum → div                     |
//! | `ascend_tile_rms_norm_f32`   | inline: x² → mean → rsqrt → mul                         |
//! | `ascend_tile_matmul_f32`     | `@math.gemm(&C, &A, &B, M, K, N);`                      |
//!
//! # Example output (softmax)
//! ```csl
//! // Generated by tile-rs mlir_to_csl — DO NOT EDIT
//! // Compile: cslc --arch=wse2 --fabric-dims=1,1 layout.csl
//! param N: i16;
//! const math = @import_module("<math>");
//! var input_tile:  [N]f32;
//! var output_tile: [N]f32;
//! task compute_task() void {
//!     var m: f32 = input_tile[0];
//!     for (@range(i16, 1, N, 1)) |i| {
//!         if (input_tile[i] > m) { m = input_tile[i]; }
//!     }
//!     var s: f32 = 0.0;
//!     for (@range(i16, 0, N, 1)) |i| {
//!         output_tile[i] = @exp(input_tile[i] - m);
//!         s = s + output_tile[i];
//!     }
//!     var inv_s: f32 = 1.0 / s;
//!     for (@range(i16, 0, N, 1)) |i| {
//!         output_tile[i] = output_tile[i] * inv_s;
//!     }
//! }
//! ```
//!
//! Run under `benchmarks/cerebras/bench_ascendrs_csl.py` on a rented
//! Cerebras Cloud or Wafer Scale Cluster node.

#[derive(Debug, Clone, Copy, PartialEq)]
enum Op {
    Load,
    Store,
    Add,
    Exp,
    Softmax,
    RmsNorm,
    Matmul,
    Unknown,
}

fn classify_callee(callee: &str) -> Op {
    if callee.contains("ascend_tile_load_") {
        Op::Load
    } else if callee.contains("ascend_tile_store_") {
        Op::Store
    } else if callee.contains("ascend_tile_add_") {
        Op::Add
    } else if callee.contains("ascend_tile_exp_") {
        Op::Exp
    } else if callee.contains("ascend_tile_softmax_") {
        Op::Softmax
    } else if callee.contains("ascend_tile_rms_norm_") {
        Op::RmsNorm
    } else if callee.contains("ascend_tile_matmul_") {
        Op::Matmul
    } else {
        Op::Unknown
    }
}

fn extract_call_callee(line: &str) -> Option<&str> {
    let at = line.find('@')?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(&rest[..end])
}

fn extract_fn_name(line: &str) -> Option<String> {
    let at = line.find('@')?;
    let rest = &line[at + 1..];
    let end = rest.find('(')?;
    Some(rest[..end].to_string())
}

fn emit_op(op: Op, out: &mut String) {
    match op {
        Op::Add => {
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        output_tile[i] = input0_tile[i] + input1_tile[i];\n");
            out.push_str("    }\n");
        }
        Op::Exp => {
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        output_tile[i] = @exp(input0_tile[i]);\n");
            out.push_str("    }\n");
        }
        Op::Softmax => {
            out.push_str("    // softmax: max → exp(x-max) → sum → div\n");
            out.push_str("    var m: f32 = input0_tile[0];\n");
            out.push_str("    for (@range(i16, 1, N, 1)) |i| {\n");
            out.push_str("        if (input0_tile[i] > m) { m = input0_tile[i]; }\n");
            out.push_str("    }\n");
            out.push_str("    var s: f32 = 0.0;\n");
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        output_tile[i] = @exp(input0_tile[i] - m);\n");
            out.push_str("        s = s + output_tile[i];\n");
            out.push_str("    }\n");
            out.push_str("    var inv_s: f32 = 1.0 / s;\n");
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        output_tile[i] = output_tile[i] * inv_s;\n");
            out.push_str("    }\n");
        }
        Op::RmsNorm => {
            out.push_str("    // rms_norm: x * rsqrt(mean(x^2) + eps)\n");
            out.push_str("    var ss: f32 = 0.0;\n");
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        ss = ss + input0_tile[i] * input0_tile[i];\n");
            out.push_str("    }\n");
            out.push_str("    var inv_rms: f32 = 1.0 / @sqrt(ss / @as(f32, N) + EPS);\n");
            out.push_str("    for (@range(i16, 0, N, 1)) |i| {\n");
            out.push_str("        output_tile[i] = input0_tile[i] * inv_rms;\n");
            out.push_str("    }\n");
        }
        Op::Matmul => {
            out.push_str("    // matmul M x K x N (dense, row-major)\n");
            out.push_str("    for (@range(i16, 0, M, 1)) |_mi| {\n");
            out.push_str("        for (@range(i16, 0, N, 1)) |_ni| {\n");
            out.push_str("            var acc: f32 = 0.0;\n");
            out.push_str("            for (@range(i16, 0, K, 1)) |_ki| {\n");
            out.push_str("                acc = acc + input0_tile[_mi * K + _ki] * input1_tile[_ki * N + _ni];\n");
            out.push_str("            }\n");
            out.push_str("            output_tile[_mi * N + _ni] = acc;\n");
            out.push_str("        }\n");
            out.push_str("    }\n");
        }
        _ => {}
    }
}

/// Convert MLIR with `ascend_tile_*` intrinsics into CSL kernel source.
pub fn convert_mlir_to_csl(mlir_text: &str) -> Result<String, String> {
    let mut fn_name: Option<String> = None;
    let mut ops: Vec<Op> = Vec::new();
    let mut n_inputs: u32 = 0;
    for raw in mlir_text.lines() {
        let line = raw.trim();
        if line.starts_with("llvm.func @") {
            fn_name = extract_fn_name(line);
            // Count !llvm.ptr<1> args to estimate number of inputs + output
            let ptrs = line.matches("!llvm.ptr<1>").count() as u32;
            if ptrs >= 2 {
                n_inputs = ptrs.saturating_sub(1); // last is output
            }
        }
        if line.contains("llvm.call @ascend_tile_") {
            if let Some(callee) = extract_call_callee(line) {
                let op = classify_callee(callee);
                if !matches!(op, Op::Unknown | Op::Load | Op::Store) {
                    ops.push(op);
                }
            }
        }
    }
    let fn_name = fn_name.unwrap_or_else(|| "tile_kernel".to_string());
    let has_matmul = ops.iter().any(|o| *o == Op::Matmul);
    let has_rms = ops.iter().any(|o| *o == Op::RmsNorm);
    let n_inputs = n_inputs.max(1).min(2);

    let mut out = String::new();
    out.push_str("// Generated by tile-rs mlir_to_csl — DO NOT EDIT\n");
    out.push_str("// Compile: cslc --arch=wse2 --fabric-dims=<X>,<Y> <layout>.csl\n");
    out.push_str("//\n");
    out.push_str("// Per-PE kernel. Host layout.csl is expected to route input tiles to\n");
    out.push_str("// `input0_color` (and `input1_color` for binary ops) and read results\n");
    out.push_str("// back from `output_color`.\n");
    out.push_str("\n");
    if has_matmul {
        out.push_str("param M: i16;\nparam K: i16;\nparam N: i16;\n");
    } else {
        out.push_str("param N: i16;\n");
    }
    if has_rms {
        out.push_str("param EPS: f32;\n");
    }
    out.push_str("\n");
    if has_matmul {
        out.push_str("var input0_tile:  [M * K]f32;\n");
        out.push_str("var input1_tile:  [K * N]f32;\n");
        out.push_str("var output_tile:  [M * N]f32;\n");
    } else if n_inputs == 2 {
        out.push_str("var input0_tile: [N]f32;\n");
        out.push_str("var input1_tile: [N]f32;\n");
        out.push_str("var output_tile: [N]f32;\n");
    } else {
        out.push_str("var input0_tile: [N]f32;\n");
        out.push_str("var output_tile: [N]f32;\n");
    }
    out.push_str("\n");
    out.push_str(&format!("// kernel: {}\n", fn_name));
    out.push_str("task compute_task() void {\n");
    for op in &ops {
        emit_op(*op, &mut out);
    }
    out.push_str("}\n");
    out.push_str("\ncomptime { @bind_local_task(compute_task, @get_task_id(@get_local_task_id(0))); }\n");
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_csl_softmax() {
        let mlir = r#"
module {
  llvm.func @tile_softmax(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %x = llvm.call @ascend_tile_load_f32(%arg0, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_softmax_f32(%x, %x, %r, %c) : (i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%arg1, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let csl = convert_mlir_to_csl(mlir).unwrap();
        assert!(csl.contains("param N: i16"));
        assert!(csl.contains("task compute_task()"));
        assert!(csl.contains("@exp(input0_tile[i] - m)"));
        assert!(csl.contains("output_tile[i] * inv_s"));
    }

    #[test]
    fn test_csl_matmul() {
        let mlir = r#"
module {
  llvm.func @tile_matmul(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>, %c: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %m = llvm.mlir.constant(128 : i32) : i32
    %k = llvm.mlir.constant(128 : i32) : i32
    %n = llvm.mlir.constant(128 : i32) : i32
    %al = llvm.call @ascend_tile_load_f32(%a, %m, %k) : (!llvm.ptr<1>, i32, i32) -> i32
    %bl = llvm.call @ascend_tile_load_f32(%b, %k, %n) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_matmul_f32(%al, %al, %bl, %m, %k, %n) : (i32, i32, i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%c, %y, %m, %n) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let csl = convert_mlir_to_csl(mlir).unwrap();
        assert!(csl.contains("param M: i16"));
        assert!(csl.contains("param K: i16"));
        assert!(csl.contains("param N: i16"));
        assert!(csl.contains("[M * K]f32"));
        assert!(csl.contains("[M * N]f32"));
    }

    #[test]
    fn test_csl_rms_norm_has_eps_param() {
        let mlir = r#"
module {
  llvm.func @tile_rms(%a: !llvm.ptr<1>, %b: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %eps = llvm.mlir.constant(1.0e-5 : f32) : f32
    %x = llvm.call @ascend_tile_load_f32(%a, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_rms_norm_f32(%x, %x, %eps, %r, %c) : (i32, i32, f32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%b, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let csl = convert_mlir_to_csl(mlir).unwrap();
        assert!(csl.contains("param EPS: f32"));
        assert!(csl.contains("+ EPS"));
        assert!(csl.contains("inv_rms"));
    }

    #[test]
    fn test_csl_add_has_two_inputs() {
        let mlir = r#"
module {
  llvm.func @tile_add(%arg0: !llvm.ptr<1>, %arg1: !llvm.ptr<1>, %arg2: !llvm.ptr<1>) attributes {hacc.entry} {
    ^bb0:
    %r = llvm.mlir.constant(1 : i32) : i32
    %c = llvm.mlir.constant(1024 : i32) : i32
    %a = llvm.call @ascend_tile_load_f32(%arg0, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %b = llvm.call @ascend_tile_load_f32(%arg1, %r, %c) : (!llvm.ptr<1>, i32, i32) -> i32
    %y = llvm.call @ascend_tile_add_f32(%a, %a, %b, %r, %c) : (i32, i32, i32, i32, i32) -> i32
    llvm.call @ascend_tile_store_f32(%arg2, %y, %r, %c) : (!llvm.ptr<1>, i32, i32, i32) -> ()
    llvm.return
  }
}
"#;
        let csl = convert_mlir_to_csl(mlir).unwrap();
        assert!(csl.contains("input0_tile"));
        assert!(csl.contains("input1_tile"));
        assert!(csl.contains("input0_tile[i] + input1_tile[i]"));
    }
}
