// Generated by tile-rs mlir_to_msl — DO NOT EDIT
// Compile: xcrun metal -c <file>.metal -o <file>.air && xcrun metallib <file>.air -o <file>.metallib
// Runtime: metal::Device::new_library_with_source(src, &CompileOptions::new())

#include <metal_stdlib>
using namespace metal;

kernel void softmax_1d(
    device const  float* p0 [[ buffer(0) ]],
    device  float* p1 [[ buffer(1) ]],
    constant uint& num_elements [[ buffer(2) ]],
    uint tid   [[ thread_position_in_threadgroup ]],
    uint row   [[ threadgroup_position_in_grid ]],
    uint tcount [[ threads_per_threadgroup ]]
)
{
    threadgroup float sdata[1024];
    uint base = row * num_elements;

    // Pass 1: find row max
    float tmax = -MAXFLOAT;
    for (uint i = tid; i < num_elements; i += tcount)
        tmax = max(tmax, p0[base + i]);
    sdata[tid] = tmax;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = tcount/2; s > 0; s >>= 1) {
        if (tid < s) sdata[tid] = max(sdata[tid], sdata[tid + s]);
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    float row_max = sdata[0];

    // Pass 2: exp(x - max), accumulate sum
    float tsum = 0.0;
    for (uint i = tid; i < num_elements; i += tcount) {
        float e = exp(p0[base + i] - row_max);
        p1[base + i] = e;
        tsum += e;
    }
    sdata[tid] = tsum;
    threadgroup_barrier(mem_flags::mem_threadgroup);
    for (uint s = tcount/2; s > 0; s >>= 1) {
        if (tid < s) sdata[tid] += sdata[tid + s];
        threadgroup_barrier(mem_flags::mem_threadgroup);
    }
    float row_sum = sdata[0];

    // Pass 3: normalise
    for (uint i = tid; i < num_elements; i += tcount)
        p1[base + i] /= row_sum;
}

