//! The PyTorch reference: the accuracy answer people actually trust.
//!
//! Comparing a kernel against a reference written in the same repository proves the two
//! agree. It does not prove either is right — a reference with the wrong formula and a
//! kernel lowered from it agree perfectly. PyTorch on the CPU is an outside opinion, and
//! outside opinions are what accuracy claims are made of.
//!
//! ## Why three sources rather than two
//!
//! With the kernel, our own scalar reference, and torch, a disagreement is *attributable*:
//!
//! | kernel vs torch | ours vs torch | what it means |
//! |---|---|---|
//! | close | close | everything agrees |
//! | far | close | **the kernel is wrong** — the lowering |
//! | far | far | **our reference is wrong** — and the kernel inherited it |
//! | close | far | our reference is wrong and the kernel does not follow it |
//!
//! Two sources cannot tell the second row from the third, and blaming a lowering for a
//! bad reference is a long afternoon.
//!
//! ## Absence
//!
//! torch is a large optional dependency and most machines running a compiler tool do not
//! have it. Its absence degrades the report to the two-way comparison and **says so** —
//! it never silently drops the stronger claim and leaves the weaker one looking
//! authoritative.

use crate::run::RefOp;
use std::fmt;

#[derive(Debug, Clone, PartialEq)]
pub enum TorchStatus {
    /// torch answered.
    Available { version: String },
    /// No python3, or torch is not importable.
    Absent { why: String },
    /// torch is here but has no equivalent for this operation.
    NoEquivalent { op: &'static str },
}

impl fmt::Display for TorchStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TorchStatus::Available { version } => write!(f, "torch {version}"),
            TorchStatus::Absent { why } => write!(
                f,
                "not available ({why}) — accuracy is reported against this tool's own \
                 reference only, which is a weaker claim"
            ),
            TorchStatus::NoEquivalent { op } => {
                write!(f, "torch has no single-call equivalent for {op}")
            }
        }
    }
}

/// The torch expression for an op, over a `(rows, cols)` tensor along the last dimension.
fn expression(op: RefOp, eps: f32) -> Option<String> {
    let e: &str = match op {
        // Matmul takes two tensors and is built by `script` itself, not by this table.
        RefOp::Matmul => return None,
        // So do min, max and matvec: this table's expressions are written over a single `x`.
        RefOp::Min | RefOp::Max | RefOp::Matvec => return None,
        RefOp::Softmax => "torch.softmax(x, dim=-1)",
        RefOp::Exp => "torch.exp(x)",
        RefOp::Sigmoid => "torch.sigmoid(x)",
        RefOp::Relu => "torch.relu(x)",
        RefOp::Sqrt => "torch.sqrt(x)",
        RefOp::Log => "torch.log(x)",
        RefOp::Neg => "torch.neg(x)",
        RefOp::Abs => "torch.abs(x)",
        RefOp::Tanh => "torch.tanh(x)",
        RefOp::Rsqrt => "torch.rsqrt(x)",
        RefOp::Silu => "torch.nn.functional.silu(x)",
        RefOp::Softplus => "torch.nn.functional.softplus(x)",
        // Reductions along the row. `keepdim=False` so the result is one value per row,
        // which is the shape the harness reads back.
        RefOp::ReduceMax => "torch.amax(x, dim=-1)",
        // eps from the SOURCE, like the kernel and the Rust reference. It was 1e-6
        // here while the emitter hardcoded 1e-6 too, and two constants agreeing is not a
        // check -- a module asking for 1e-3 was compared against torch computing 1e-6.
        RefOp::RmsNorm => {
            return Some(format!(
                "x * torch.rsqrt(torch.mean(x * x, dim=-1, keepdim=True) + {eps:e})"
            ))
        }
        RefOp::ReduceSum => "torch.sum(x, dim=-1)",
        RefOp::Absmax => "torch.amax(torch.abs(x), dim=-1)",
    };
    Some(e.to_string())
}

/// The script. The input is generated by the same rule as the harness and this tool's own
/// reference — written here rather than passed in, so a shell quoting mistake cannot
/// silently feed torch different numbers.
pub fn script(op: RefOp, shape: crate::run::Shape, eps: f32, dtype: &str) -> Option<String> {
    use crate::run::Shape;
    // #010. `metal.swift` writes an f16 kernel's inputs as `Float16(v[i])`, so torch and
    // the Rust reference must see the same rounded values or the comparison is of two
    // different problems. `.half().float()` here is the same rounding `quantize_inputs`
    // applies on the Rust side; both are checked against numpy.
    //
    // It goes on the INPUTS only. Making torch compute in half as well would model the
    // kernel's arithmetic too, and then no reference would be independent of it -- the
    // accumulation is what `error_budget` accounts for, separately and on purpose.
    let q = if dtype == "half" {
        ".half().float()"
    } else {
        ""
    };
    if let Shape::Matmul { m, k, n } = shape {
        // The real (m, k, n), taken from the same `Shape` the device harness is driven
        // with. It used to be `m=rows, k=cols, n=cols` -- square by assumption -- which
        // agreed with the kernel only as long as nobody ran a non-square matmul, and
        // would otherwise have compared two different products.
        return Some(format!(
            "import sys\n\
             try:\n    import torch\n\
             except Exception as e:\n    print('#absent', e, file=sys.stderr); sys.exit(3)\n\
             print('#version', torch.__version__)\n\
             m = {m}; k = {k}; n = {n}\n\
             a = [ (i % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(m*k) ]\n\
             b = [ ((i + 7) % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(k*n) ]\n\
             x = torch.tensor(a, dtype=torch.float32){q}.reshape(m, k)\n\
             y = torch.tensor(b, dtype=torch.float32){q}.reshape(k, n)\n\
             z = torch.matmul(x, y)\n\
             for f in z.flatten().tolist():\n    print('%.9e' % f)\n"
        ));
    }
    if let Shape::Matvec { rows, cols } = shape {
        // Matrix (rows, cols) from buffer 0, vector (cols,) from buffer 1 -- the same two
        // generators the Rust reference and the device harness use.
        return Some(format!(
            "import sys\n\
             try:\n    import torch\n\
             except Exception as e:\n    print('#absent', e, file=sys.stderr); sys.exit(3)\n\
             print('#version', torch.__version__)\n\
             rows = {rows}; cols = {cols}\n\
             a = [ (i % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(rows*cols) ]\n\
             b = [ ((i + 7) % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(cols) ]\n\
             x = torch.tensor(a, dtype=torch.float32){q}.reshape(rows, cols)\n\
             y = torch.tensor(b, dtype=torch.float32){q}\n\
             z = torch.mv(x, y)\n\
             for v in z.flatten().tolist():\n    print('%.9e' % v)\n"
        ));
    }
    if let Shape::Rows2 { rows, cols } = shape {
        // Two tiles of the same extent, generated by the same rule as the Rust reference
        // and the device harness: buffer 0 is `(i % 17)`, buffer 1 is `((i + 7) % 17)`.
        // The three must agree on the inputs or the comparison is of different problems.
        let f = match op {
            RefOp::Min => "torch.minimum(x, y)",
            RefOp::Max => "torch.maximum(x, y)",
            _ => return None,
        };
        return Some(format!(
            "import sys\n\
             try:\n    import torch\n\
             except Exception as e:\n    print('#absent', e, file=sys.stderr); sys.exit(3)\n\
             print('#version', torch.__version__)\n\
             rows = {rows}; cols = {cols}\n\
             a = [ (i % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(rows*cols) ]\n\
             b = [ ((i + 7) % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(rows*cols) ]\n\
             x = torch.tensor(a, dtype=torch.float32){q}.reshape(rows, cols)\n\
             y = torch.tensor(b, dtype=torch.float32){q}.reshape(rows, cols)\n\
             z = {f}\n\
             for v in z.flatten().tolist():\n    print('%.9e' % v)\n"
        ));
    }
    let (rows, cols) = match shape {
        Shape::Rows { rows, cols } => (rows, cols),
        // A reduction reshapes to (rows, cols) exactly as an elementwise op does; the
        // expression itself is what collapses the last dimension.
        Shape::RowReduce { rows, cols } => (rows, cols),
        // Both are built above, each from two tensors rather than one.
        Shape::Matmul { .. } | Shape::Rows2 { .. } | Shape::Matvec { .. } => return None,
    };
    let expr = expression(op, eps)?;
    Some(format!(
        "import sys\n\
         try:\n    import torch\n\
         except Exception as e:\n    print('#absent', e, file=sys.stderr); sys.exit(3)\n\
         print('#version', torch.__version__)\n\
         n = {rows} * {cols}\n\
         v = [ (i % 17) * 0.25 - 2.0 + i * 1e-4 for i in range(n) ]\n\
         x = torch.tensor(v, dtype=torch.float32){q}.reshape({rows}, {cols})\n\
         y = {expr}\n\
         for f in y.flatten().tolist():\n    print('%.9e' % f)\n"
    ))
}

/// How the reference was obtained, so the report can say.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Via {
    /// A `python3` on PATH that already has torch.
    SystemPython,
    /// `uv run --with torch`, which resolves and caches torch itself.
    Uv,
}

/// A `uv` we can call: one on PATH, or one this tool provisioned.
pub fn uv_command() -> Option<std::path::PathBuf> {
    if std::process::Command::new("uv")
        .arg("--version")
        .output()
        .is_ok_and(|o| o.status.success())
    {
        return Some("uv".into());
    }
    let root = crate::provision::home().join("toolchains/uv");
    let rd = std::fs::read_dir(&root).ok()?;
    for e in rd.flatten() {
        for candidate in [e.path().join("uv"), e.path().join("bin/uv")] {
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }
    None
}

/// Ask torch. `Err` carries why it could not be asked, which is not a failure.
///
/// Three ways, in order of what they cost the user:
///
/// 1. a `python3` on PATH that already has torch — instant, no network;
/// 2. `uv run --with torch` — uv resolves and caches torch itself, so there is no venv to
///    create and no second command for anyone to run. This is the "no additional
///    commands" path;
/// 3. provision `uv` first, verified against a pinned digest, then (2).
///
/// Step 3 downloads, so it is announced and obeys `--offline` / `--no-install`. Nothing
/// here is `curl | sh`: uv arrives through the same manifest as every other toolchain.
pub fn reference(
    op: RefOp,
    shape: crate::run::Shape,
    // From the MLIR, so torch, the Rust reference and the kernel share one number.
    eps: f32,
    // The kernel's BUFFER type, so torch sees the same rounded inputs the device does.
    dtype: &str,
    policy: crate::provision::Policy,
    report: &mut dyn FnMut(&str),
) -> Result<(String, Vec<f32>, Via), TorchStatus> {
    let Some(src) = script(op, shape, eps, dtype) else {
        return Err(TorchStatus::NoEquivalent { op: op.name() });
    };

    // 1. Already there? Costs nothing to ask.
    if let Ok(out) = std::process::Command::new("python3")
        .arg("-c")
        .arg(&src)
        .output()
    {
        if out.status.success() {
            let (v, vals) = parse(&String::from_utf8_lossy(&out.stdout));
            if !vals.is_empty() {
                return Ok((v, vals, Via::SystemPython));
            }
        }
    }

    // 2/3. uv, provisioning it first if it is not here.
    let uv = match uv_command() {
        Some(u) => u,
        None => {
            let (os, arch) = (std::env::consts::OS, std::env::consts::ARCH);
            match crate::provision::ensure("uv", os, arch, policy, report) {
                Ok(_) => uv_command().ok_or(TorchStatus::Absent {
                    why: "uv was installed but could not be found afterwards".into(),
                })?,
                Err(e) => {
                    return Err(TorchStatus::Absent {
                        why: format!("no torch, and uv could not be installed: {e}"),
                    })
                }
            }
        }
    };

    report("asking torch through uv (the first run resolves and caches it)");
    let out = std::process::Command::new(&uv)
        .args(["run", "--quiet", "--with", "torch", "python", "-c"])
        .arg(&src)
        .output()
        .map_err(|e| TorchStatus::Absent {
            why: format!("uv: {e}"),
        })?;
    if !out.status.success() {
        let why = String::from_utf8_lossy(&out.stderr)
            .lines()
            .last()
            .unwrap_or("uv exited non-zero")
            .trim()
            .to_string();
        return Err(TorchStatus::Absent { why });
    }
    let (v, vals) = parse(&String::from_utf8_lossy(&out.stdout));
    if vals.is_empty() {
        return Err(TorchStatus::Absent {
            why: "uv ran but torch produced no values".into(),
        });
    }
    Ok((v, vals, Via::Uv))
}

/// Split the script's output into (version, values).
pub fn parse(text: &str) -> (String, Vec<f32>) {
    let mut version = String::from("(unknown)");
    let mut values = Vec::new();
    for line in text.lines() {
        if let Some(rest) = line.strip_prefix("#version ") {
            version = rest.trim().to_string();
        } else if !line.starts_with('#') && !line.trim().is_empty() {
            if let Ok(v) = line.trim().parse::<f32>() {
                values.push(v);
            }
        }
    }
    (version, values)
}

/// How far apart two vectors are, in the three ways that matter for f32.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Accuracy {
    pub compared: usize,
    pub max_abs: f32,
    /// Relative error, skipping elements whose reference is too small for a ratio to
    /// mean anything — near zero every implementation disagrees relatively and none of
    /// them is wrong.
    pub max_rel: f32,
    pub rmse: f32,
    /// Elements where one side is NaN or infinite and the other is not.
    pub non_finite: usize,
    /// The largest absolute error among elements whose reference is too SMALL for a ratio
    /// to mean anything -- the ones `max_rel` skips.
    ///
    /// `within` used to require `max_abs <= abs_tol && max_rel <= rel_tol`, which is
    /// stricter than `numpy.allclose` and wrong wherever the output's scale varies:
    /// `rsqrt` over a row containing a value near zero produces a huge result, so a
    /// relative error of 1.64e-5 shows up as an absolute 6.7e-4 and failed a 1e-5 gate.
    /// This tool's OWN reference failed it, against torch, which is the same signal #013
    /// gave for reductions.
    ///
    /// With this, each element is judged by the measure that means something for it:
    /// relative where the reference is large enough for a ratio, absolute where it is not.
    pub max_abs_near_zero: f32,
}

impl Accuracy {
    pub fn of(got: &[f32], want: &[f32]) -> Accuracy {
        let n = got.len().min(want.len());
        let (mut max_abs, mut max_rel, mut sq, mut non_finite) = (0.0f32, 0.0f32, 0.0f64, 0usize);
        let mut max_abs_near_zero = 0.0f32;
        for i in 0..n {
            let (g, w) = (got[i], want[i]);
            if g.is_finite() != w.is_finite() {
                non_finite += 1;
                continue;
            }
            if !g.is_finite() {
                continue;
            }
            let d = (g - w).abs();
            if d > max_abs {
                max_abs = d;
            }
            // A relative error against a value near zero is arbitrarily large and says
            // nothing; the floor keeps the figure meaningful rather than alarming. The
            // elements below the floor are not ignored -- they are judged absolutely.
            if w.abs() > 1e-6 {
                let r = d / w.abs();
                if r > max_rel {
                    max_rel = r;
                }
            } else if d > max_abs_near_zero {
                max_abs_near_zero = d;
            }
            sq += (d as f64) * (d as f64);
        }
        Accuracy {
            compared: n,
            max_abs,
            max_rel,
            rmse: if n > 0 {
                (sq / n as f64).sqrt() as f32
            } else {
                0.0
            },
            non_finite,
            max_abs_near_zero,
        }
    }

    /// Is this within what f32 arithmetic can be expected to reproduce?
    pub fn within(&self, abs_tol: f32, rel_tol: f32) -> bool {
        // Each element by the measure that means something for it. Requiring BOTH bounds
        // over the whole vector rejected agreement wherever the output's scale varies --
        // `rsqrt` near zero is large, so 1.64e-5 relative reads as 6.7e-4 absolute, and
        // this tool's own reference failed its own gate against torch.
        self.non_finite == 0
            && self.max_rel <= rel_tol
            && self.max_abs_near_zero <= abs_tol
            // A vector with NO element above the ratio floor has no relative measure at
            // all, and `max_rel` stays 0. Its absolute error still has to pass.
            && (self.max_rel > 0.0 || self.max_abs <= abs_tol)
    }

    pub fn render(&self) -> String {
        let nf = if self.non_finite > 0 {
            format!("  NON-FINITE MISMATCHES {}", self.non_finite)
        } else {
            String::new()
        };
        format!(
            "max abs {:.2e}  max rel {:.2e}  rmse {:.2e}{nf}",
            self.max_abs, self.max_rel, self.rmse
        )
    }
}

/// What "agrees" is allowed to mean for this operation.
///
/// #013: `ABS_TOL`/`REL_TOL` were applied to everything, so a K-term reduction was judged
/// by a number chosen for elementwise arithmetic and no correct lowering could pass. The
/// choice is made once, here, and every consumer reads it -- there were three hardcoded
/// tolerances before this (the pair in `render`, the `tolerance` field, and `worst > 1e-4`
/// deciding the exit code), which is the drift this project keeps finding.
#[derive(Debug, Clone, Copy)]
pub enum Tolerance {
    /// For ops whose error does not grow with anything.
    Fixed { abs: f32, rel: f32 },
    /// For ops that sum. Judged on the ABSOLUTE bound alone: a relative error taken
    /// against a heavily cancelled sum is large for correct arithmetic and says nothing
    /// about the kernel.
    Summation(crate::run::Budget),
}

impl Tolerance {
    pub fn admits(&self, a: &Accuracy) -> bool {
        match self {
            Tolerance::Fixed { abs, rel } => a.within(*abs, *rel),
            Tolerance::Summation(b) => a.non_finite == 0 && a.max_abs <= b.guaranteed,
        }
    }

    /// The absolute number a caller may compare a single error against.
    pub fn abs(&self) -> f32 {
        match self {
            Tolerance::Fixed { abs, .. } => *abs,
            Tolerance::Summation(b) => b.guaranteed,
        }
    }
}

/// Which side a disagreement points at.
///
/// The whole reason for a third opinion: two sources cannot tell "the kernel is wrong"
/// from "our reference is wrong and the kernel faithfully reproduced it".
pub fn attribute(
    kernel_vs_torch: &Accuracy,
    ours_vs_torch: &Accuracy,
    kernel_vs_ours: &Accuracy,
    tol: Tolerance,
) -> &'static str {
    let k = tol.admits(kernel_vs_torch);
    let o = tol.admits(ours_vs_torch);
    // The third comparison decides what "inherited" is allowed to mean. It was computed
    // and printed on the line above the verdict, and not passed in -- so the one
    // measurement that can tell "the kernel copied our mistake" from "everything
    // disagrees with everything" was the one the attribution could not see.
    let same_mistake = tol.admits(kernel_vs_ours);
    match (k, o) {
        (true, true) => "all three agree",
        (false, true) => "the KERNEL disagrees with torch — look at the lowering",
        (false, false) if same_mistake => {
            "this tool's own reference disagrees with torch too, and the kernel matches \
             the reference — the reference is wrong and the kernel inherited it"
        }
        (false, false) => {
            // Claiming the kernel "inherited" the reference's error here would be false:
            // it does not agree with the reference either. Observed on a kernel that was
            // wrong by 100% while the reference sat 3.29e-4 from torch -- ordinary f16
            // accumulation, blamed as the cause.
            //
            // It does not say "separate faults" any more, which was the same overreach in
            // the other direction. An f32 matmul over K=64 lands here with all three
            // figures the same ORDER -- kernel 1.14e-5, reference 9.54e-6 against torch --
            // and that is summation order, not a fault in anything. Three comparable
            // disagreements mean the tolerance is tighter than the operation's own
            // precision; one that dwarfs the others means a defect. The line reports which
            // it is looking at rather than naming a culprit it cannot identify.
            if matches!(tol, Tolerance::Summation(_)) {
                // Under a derived bound this sentence means something stronger than it did
                // under a fixed one. The bound is what NO summation order can exceed, so
                // "three of a size is the operation's own precision" is no longer an
                // available reading: all three being outside it means all three are
                // outside what f32 summation can explain.
                "all three disagree, and all three are outside what f32 summation of this \
                 length can produce — this is not summation order, look at the inputs the \
                 harness fed each side"
            } else {
                "all three disagree, including the kernel against the reference — compare \
                 the three magnitudes above: one much larger than the others is a defect, \
                 three of a size is the operation's own precision against this tolerance"
            }
        }
        (true, false) => {
            "the kernel matches torch but this tool's reference does not — the reference \
             is wrong and the kernel does not follow it"
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// #010. The harness writes an f16 kernel's inputs as `Float16(v[i])`; both
    /// references used the f32 originals, so the kernel was compared against numbers it
    /// was never given. Three implementations of the input rule means three places this
    /// can drift, so the f16 rounding is checked in the script the same way the values
    /// themselves are.
    #[test]
    fn an_f16_kernel_gets_references_computed_on_f16_inputs() {
        let shape = crate::run::Shape::Rows { rows: 4, cols: 8 };
        let f32s = script(RefOp::Softmax, shape, 1e-6, "float").expect("a script");
        let f16s = script(RefOp::Softmax, shape, 1e-6, "half").expect("a script");
        assert!(
            !f32s.contains(".half()"),
            "an f32 kernel's reference must not round its inputs:\n{f32s}"
        );
        assert!(
            f16s.contains("torch.tensor(v, dtype=torch.float32).half().float()"),
            "an f16 kernel's reference must see the values the device sees:\n{f16s}"
        );
        // The Rust reference rounds the same way. Checked by VALUE rather than by reading
        // both implementations and believing they agree.
        let mut v = crate::run::input_values(64);
        crate::run::quantize_inputs(&mut v, "half");
        let plain = crate::run::input_values(64);
        assert!(
            v != plain,
            "these inputs are not all f16-representable, or the check proves nothing"
        );
        for (q, p) in v.iter().zip(plain.iter()) {
            assert_eq!(*q, crate::run::f16_round(*p));
        }
        // And an f32 kernel is left alone.
        let mut u = crate::run::input_values(64);
        crate::run::quantize_inputs(&mut u, "float");
        assert_eq!(u, plain);
    }

    #[test]
    fn the_script_generates_the_same_input_as_the_harness_and_the_reference() {
        // Three implementations of one rule is two chances to drift. They are checked
        // against each other rather than trusted.
        let s = script(
            RefOp::Softmax,
            crate::run::Shape::Rows { rows: 1, cols: 8 },
            1e-6,
            "float",
        )
        .expect("a script");
        assert!(s.contains("(i % 17) * 0.25 - 2.0"), "{s}");
        // The matmul script generates a SECOND buffer; it must use the same offset rule.
        let mm = script(
            RefOp::Matmul,
            crate::run::Shape::Matmul { m: 2, k: 2, n: 2 },
            1e-6,
            "float",
        )
        .expect("a matmul script");
        assert!(mm.contains("((i + 7) % 17) * 0.25 - 2.0"), "{mm}");
        let ours = crate::run::input_values(8);
        assert_eq!(ours[0], -2.0);
        let swift = include_str!("../assets/harness/metal.swift");
        assert!(swift.contains("Float(($0 + 7 * b + seed) % 17) * 0.25 - 2.0"));
    }

    #[test]
    fn every_referenceable_op_has_a_torch_expression() {
        for op in [
            RefOp::Softmax,
            RefOp::Exp,
            RefOp::Sigmoid,
            RefOp::Relu,
            RefOp::Sqrt,
            RefOp::Log,
            RefOp::Neg,
            RefOp::Abs,
        ] {
            assert!(
                expression(op, 1e-6).is_some(),
                "{} has no torch equivalent",
                op.name()
            );
        }
    }

    #[test]
    fn the_script_reduces_along_the_last_dimension() {
        // A softmax over the wrong axis produces plausible numbers that are entirely
        // wrong, and it would read as a kernel bug.
        let s = script(
            RefOp::Softmax,
            crate::run::Shape::Rows { rows: 4, cols: 8 },
            1e-6,
            "float",
        )
        .unwrap();
        assert!(s.contains("dim=-1"), "{s}");
        assert!(s.contains("reshape(4, 8)"), "{s}");
    }

    #[test]
    fn uv_is_pinned_in_the_manifest_for_every_platform_we_ship_to() {
        // Not `curl -LsSf https://astral.sh/uv/install.sh | sh`: that pipe is unverified,
        // runs whatever the server sends, and installs wherever it likes.
        let tools = crate::manifest::builtin();
        for (os, arch) in [
            ("macos", "aarch64"),
            ("macos", "x86_64"),
            ("linux", "x86_64"),
            ("linux", "aarch64"),
        ] {
            let t = crate::manifest::find(&tools, "uv", os, arch)
                .unwrap_or_else(|| panic!("no uv entry for {os}/{arch}"));
            assert!(t.pinned(), "uv on {os}/{arch} has no real digest");
            assert!(t.auto_installable(), "uv on {os}/{arch} would not install");
            assert_eq!(t.unpack.as_deref(), Some("tar.gz"));
        }
    }

    #[test]
    fn output_is_parsed_into_a_version_and_values() {
        let (v, vals) = parse("#version 2.4.1\n1.0e+00\n-2.5e-01\n");
        assert_eq!(v, "2.4.1");
        assert_eq!(vals, vec![1.0, -0.25]);
    }

    #[test]
    fn an_absent_torch_is_reported_as_a_weaker_claim_not_a_failure() {
        let s = TorchStatus::Absent {
            why: "No module named 'torch'".into(),
        };
        let msg = s.to_string();
        assert!(msg.contains("weaker claim"), "{msg}");
        // It must never silently drop the stronger claim and leave the weaker one
        // looking authoritative.
        assert!(msg.contains("own reference only"), "{msg}");
    }

    #[test]
    fn identical_vectors_have_no_error() {
        let a = vec![1.0f32, 2.0, 3.0];
        let acc = Accuracy::of(&a, &a);
        assert_eq!(acc.max_abs, 0.0);
        assert_eq!(acc.rmse, 0.0);
        assert!(acc.within(1e-6, 1e-6));
    }

    #[test]
    fn a_relative_error_near_zero_does_not_dominate_the_figure() {
        // Near zero every implementation disagrees relatively and none is wrong.
        let got = vec![1e-9f32, 1.0];
        let want = vec![1e-12f32, 1.0];
        let acc = Accuracy::of(&got, &want);
        assert_eq!(acc.max_rel, 0.0, "a tiny reference produced a huge ratio");
        assert!(acc.max_abs < 1e-8);
    }

    #[test]
    fn a_nan_against_a_number_is_counted_rather_than_averaged_away() {
        // NaN in an RMSE poisons the whole figure into NaN and says nothing about how
        // many elements were affected.
        let acc = Accuracy::of(&[f32::NAN, 1.0], &[0.5, 1.0]);
        assert_eq!(acc.non_finite, 1);
        assert!(acc.rmse.is_finite(), "one NaN poisoned the summary");
        assert!(
            !acc.within(1.0, 1.0),
            "a non-finite mismatch can never be within tolerance"
        );
        assert!(acc.render().contains("NON-FINITE"), "{}", acc.render());
    }

    #[test]
    fn three_sources_attribute_a_disagreement_to_the_right_side() {
        let close = Accuracy {
            compared: 4,
            max_abs: 1e-8,
            max_rel: 1e-8,
            rmse: 1e-8,
            non_finite: 0,
            max_abs_near_zero: 0.0,
        };
        let far = Accuracy {
            compared: 4,
            max_abs: 1.0,
            max_rel: 1.0,
            rmse: 1.0,
            non_finite: 0,
            max_abs_near_zero: 0.0,
        };
        let tol = Tolerance::Fixed {
            abs: 1e-5,
            rel: 1e-4,
        };
        assert_eq!(attribute(&close, &close, &close, tol), "all three agree");
        assert!(attribute(&far, &close, &close, tol).contains("KERNEL disagrees"));

        // The kernel reproduced our reference's error: both differ from torch and agree
        // with each other. "Inherited" is a true claim here.
        assert!(
            attribute(&far, &far, &close, tol).contains("inherited it"),
            "kernel matching a wrong reference is the inheritance case"
        );

        // Everything disagrees with everything. Attribution used to be given only the
        // first two comparisons, so it could not tell this apart from the case above and
        // announced that the reference was wrong and the kernel inherited it. Observed on
        // a real kernel that was wrong by 100% while the reference sat 3.29e-4 from torch
        // -- ordinary f16 accumulation, reported as the cause of a total miscompute.
        let verdict = attribute(&far, &far, &far, tol);
        assert!(
            !verdict.contains("inherited"),
            "the kernel does not match the reference, so it inherited nothing: {verdict}"
        );
        assert!(verdict.contains("compare the"), "{verdict}");
        assert!(attribute(&far, &far, &close, tol).contains("reference is wrong"));
        assert!(attribute(&close, &far, &far, tol).contains("does not follow it"));
    }

    /// The both-disagree line must not name a culprit it cannot identify.
    ///
    /// It said "they are separate faults", which is as much an overreach as the
    /// "inherited" claim it replaced. An f32 matmul over K=64 lands in this corner with all
    /// three figures the same order -- kernel 1.14e-5 and reference 9.54e-6 against torch --
    /// which is summation order, not a fault in anything. The distinction the reader needs
    /// is magnitude, so that is what it points at.
    #[test]
    fn the_both_disagree_line_describes_rather_than_diagnoses() {
        let acc = |e: f32| Accuracy {
            compared: 4,
            max_abs: e,
            max_rel: e,
            rmse: e,
            non_finite: 0,
            max_abs_near_zero: 0.0,
        };
        let tol = Tolerance::Fixed {
            abs: 1e-5,
            rel: 1e-4,
        };
        let v = attribute(&acc(1.0), &acc(1.0), &acc(1.0), tol);
        assert!(!v.contains("fault"), "must not assert a fault: {v}");
        assert!(!v.contains("inherited"), "nothing was inherited: {v}");
        assert!(
            v.contains("precision") && v.contains("defect"),
            "it should name both readings and let the magnitudes decide: {v}"
        );
    }

    #[test]
    fn the_two_source_case_cannot_make_the_attribution_the_three_source_case_can() {
        // The argument for asking torch at all, written as a test: `far` against our own
        // reference is the SAME observation in the second and third rows of the table.
        let close = Accuracy {
            compared: 4,
            max_abs: 1e-8,
            max_rel: 1e-8,
            rmse: 1e-8,
            non_finite: 0,
            max_abs_near_zero: 0.0,
        };
        let far = Accuracy {
            compared: 4,
            max_abs: 1.0,
            max_rel: 1.0,
            rmse: 1.0,
            non_finite: 0,
            max_abs_near_zero: 0.0,
        };
        let tol = Tolerance::Fixed {
            abs: 1e-5,
            rel: 1e-4,
        };
        assert_ne!(
            attribute(&far, &close, &far, tol),
            attribute(&far, &far, &close, tol)
        );
    }
}
